/**
 * El catálogo de figuras de la masa de la portada: ideas hechas realidad.
 * GENERADO por scripts/portada/hornear_figuras.ts a partir de
 * scripts/portada/dibujos.ts; no se edita a mano. Cada nombre tiene su campo
 * precalculado en public/portada/figuras/<nombre>.bin (128 x 128, 16 bits).
 */
export const FIGURAS = [
  "cafeteria",
  "bicicleta",
  "maceta",
  "panaderia",
  "laptop",
  "foodtruck",
  "tienda",
  "cohete",
  "guitarra",
  "velero",
  "camara",
  "casahuerto",
  "libro",
  "tijeras",
  "camiseta",
  "pastel",
  "pizza",
  "helado",
  "dron",
  "regadera",
  "perro",
  "pez",
  "zapato",
  "anteojos",
  "microfono",
  "audifonos",
  "paleta",
  "costura",
  "carpa",
  "carrito",
  "paquete",
  "camion",
  "aerogenerador",
  "panelsolar",
  "olla",
  "tetera",
  "miel",
  "vela",
  "lapizregla",
  "birrete",
  "globo",
  "telescopio",
  "telefono",
  "mecanica",
  "edificio",
  "faro",
  "cupcake",
  "hamburguesa",
  "mancuerna",
  "reloj",
  "lampara",
  "tractor",
] as const;

export type NombreFigura = (typeof FIGURAS)[number];
