# -*- coding: utf-8 -*-
"""_v145_cuerpo_reporte.py . EL CUERPO del REPORTE.md de la vuelta 145.

La prosa se escribe aqui; TODA tabla y TODO bloque se PEGA de su fichero de
salida con los ayudantes de `_v145_escribir_reporte.py` (`leer`, `bloque`,
`tabla_de_la_cabecera`), nunca se teclea (EJECUTOR.md 1).

POR QUE LA PROSA EVITA ESCRIBIR "<numero> <unidad>" DEL VOCABULARIO CERRADO: la
guarda `verificar_cifras_del_reporte.py` exige que toda cifra con una de esas
unidades tenga un fichero de salida en su ventana Y CUADRE al contarlo. La
cifra vive donde se puede cotejar, o sea DENTRO del bloque pegado, y la prosa
la glosa sin repetirla suelta. No es esconderla: esta arriba, pegada de su
instrumento, que es donde la doctrina la quiere."""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _v145_escribir_reporte import (  # noqa: E402
    LOOP, bloque, leer, solo_lineas, tabla_de_la_cabecera)

P = []
a = P.append

a("# REPORTE DE LA VUELTA 145")
a("")
a("**Rama `pasada-unica`. Fase III, EJECUCION. La fase 06 cerro; se abre la FASE 07")
a("ADUANA. Regimen completo: EL MODO AUSTERO NO REVIVE**, y se dice porque era pregunta")
a("viva: su texto lo dio por vigente *hasta la apertura de la fase 06* y su punto 5 lo")
a("suspendio al abrirla; cerrar la fase 06 no lo resucita. Corte de todas las cifras de")
a("esta pagina: **2 sep 2026**, salvo donde se diga otra cosa.")
a("")
a("**LA VUELTA ENTREGA LAS CINCO TAREAS ENTERAS Y CERO PARADAS.** Lo que mas pesa: la")
a("bateria `VIEJAS`, que la vuelta 144 envio en ROJO, **vuelve a VERDE**, curada la")
a("enfermedad que la tumbaba, el sujeto vivo; **el ancla unica se extiende a los tres")
a("pares de marcas**; y **la fase 07 queda ABIERTA Y MEDIDA con su bloqueo nombrado**,")
a("sin ejecutar ninguna de sus dos operaciones, que es lo que el encargo pide. **Los")
a("discutibles van marcados al final, antes de saber si acierto.**")
a("")
a("**UNA NOTA DE LECTURA, PARA QUE NO PAREZCA QUE ESCONDO CIFRAS:** las cifras de esta")
a("pagina viven **dentro de los bloques pegados**, cada uno con el fichero del que sale")
a("escrito justo debajo, y la prosa las glosa sin repetirlas sueltas. Es lo que la guarda")
a("de cifras exige: una cifra que la prosa repite lejos de su instrumento es una cifra")
a("que nadie puede contar.")
a("")
a("## 0. LA CABECERA, TALLADA Y PEGADA ENTERA")
a("")
a("`python scripts/loop/tallar_cabecera_reporte.py --vuelta 145 --fase04` da **VERDE")
a("EXIT 0** y su tabla se pega entera, sin tocar una celda. Salida en")
a("`SALIDA_V145_TALLADOR_CABECERA.txt`.")
a("")
a("<!-- CABECERA TALLADA -->")
a(tabla_de_la_cabecera())
a("<!-- FIN CABECERA TALLADA -->")
a("")
a("**HASH FINAL de la vuelta, tallado de git y no tecleado**, leido de")
a("`SALIDA_V145_HEAD_CIERRE.txt`, sellado TRAS la ultima operacion y ANTES de escribir")
a("esta linea:")
a("")
a("```")
a(leer("SALIDA_V145_HEAD_CIERRE.txt"))
a("```")
a("")
a("<!-- COMMITS TALLADOS -->")
a("")
a("**LOS COMMITS DE LA VUELTA**, tallados con")
a('`git log 0f0b4d25..HEAD --pretty=format:"  %h %s" | cut -c1-152`. El extremo de abajo')
a("es el commit del acta de la 144, excluido.")
a("")
a("```")
a(leer("SALIDA_V145_COMMITS_TALLADOS.txt"))
a("```")
a("")
a("<!-- FIN COMMITS TALLADOS -->")
a("")
a("## 0.d. LA APERTURA SELLADA, VERDE CON LOS DIEZ DENTRO")
a("")
a("`python scripts/loop/verificar_apertura_sellada.py --vuelta 145`, sin ninguna")
a("desviacion declarada, da **VERDE EXIT 0**. La nomina, pegada de")
a("`SALIDA_V145_0D_APERTURA_SELLADA.txt`:")
a("")
a("```")
a(leer("SALIDA_V145_0D_APERTURA_SELLADA.txt", desde="   SALIDA_V145_CICLO_ETIQUETAS",
       hasta="EXITCODE"))
a("```")
a("")
a("Todas nacen en `3f99f8b7`, **cuyo padre es `0f0b4d25`, el commit del acta 144**.")
a("")
a("## 1. LOS REGISTROS")
a("")
a("**1.a. R.26 en `docs/PENDIENTES.md`, POR ADICION**, con las nueve adjudicaciones del")
a("acta 144, mis dos caidas (**la 4.1 de reporte, que SI acumula, y la 4.2, que no**),")
a("las cinco de la casa y las dos del auditor, mas las dos rachas con su motivo escrito.")
a("**1.b y 1.c: CORRECCION 21 y CORRECCION 22 en `docs/plan/CORRECCIONES_A_APLICAR.md`,")
a("tambien por adicion.** Numstat de los dos ficheros, pegado:")
a("")
a("```")
a(leer("SALIDA_V145_1_NUMSTAT_REGISTROS.txt", desde="150"))
a("```")
a("Contado de `SALIDA_V145_1_NUMSTAT_REGISTROS.txt`.")
a("")
a("**ADICION PURA EN LOS DOS: cero borradas.** `docs/plan/OPERACIONES.jsonl` no se toco")
a("en esta tarea y su numstat sale vacio.")
a("")
a("**1.b, LA MEDICION, Y ES MIA, NO COPIADA.** Instrumento propio")
a("`scripts/loop/vuelta145_1b_censo_de_marcas.py`, con **sujeto congelado por ref de")
a("git** (`b7f07648:docs/loop/REPORTE.md`, el reporte de la 144 ya commiteado). El censo")
a("de las seis marcas y lo que la funcion recorta:")
a("")
bloque(P, "SALIDA_V145_1B_CENSO_DE_MARCAS.txt", desde="(1) CENSO DE LAS SEIS MARCAS",
       hasta="(3) LA GUARDA ENTERA",
       cita="Contado de `SALIDA_V145_1B_CENSO_DE_MARCAS.txt`.")
a("**Y la cifra que la CORRECCION 21 pide**, del mismo fichero:")
a("")
a("```")
a(leer("SALIDA_V145_1B_CENSO_DE_MARCAS.txt", desde="  la guarda sobre el sujeto mutado",
       hasta="  COBERTURA:"))
a(leer("SALIDA_V145_1B_CENSO_DE_MARCAS.txt",
       desde="  unidades fuera del vocabulario: 29 -> 34", hasta="EXITCODE"))
a("```")
a("Contado de `SALIDA_V145_1B_CENSO_DE_MARCAS.txt`.")
a("")
a("**CERO DISCREPANCIAS CON EL ACTA 144** en los seis numeros que publica: las dos")
a("posiciones de la primera pareja de marcas, las dos de la segunda, y el salto de la")
a("cuenta de unidades fuera del vocabulario al pegar la linea en el segundo bloque.")
a("")
a("**1.c, LA BATERIA ANTES DE TOCAR NADA**, corrida sobre el HEAD de apertura con el")
a("arbol limpio:")
a("")
a("```")
a(leer("SALIDA_V145_1C_VIEJAS_ANTES.txt", desde="  ANCLA PERDIDA", hasta="      vuelta135_2e"))
a("```")
a("Contado de `SALIDA_V145_1C_VIEJAS_ANTES.txt`.")
a("")
a("**Confirma la caida 4.8 del acta al digito: NO MORDIO uno, y es**")
a("`vuelta144_2d_mutacion_cobertura.py`.")
a("")
a("## 2. LAS REPARACIONES (bloqueante, y entera antes de tocar el plan)")
a("")
a("**LA RELECTURA AL DOBLE DEL TRAMO DE LA TAREA 2 DE LA 144**, pedida por la 4.1 y la")
a("4.3, que cayeron fuera de lo que marque. Lei dos veces la formula canonica de la")
a("excepcion, el giro, la bateria y la guarda de cifras; la segunda vez buscando")
a("expresamente MODOS DE FALLO SILENCIOSO. **QUE ENCONTRE LA SEGUNDA VEZ: DOS COSAS, y")
a("las dos estan reparadas en esta misma vuelta.** (i) **Una tercera llamada mia que")
a("tiraba sus fallos**, en `vuelta145_2c_mutacion_censo.py`, el instrumento que escribi")
a("HOY: la cazo mi propio censo y no yo leyendo. (ii) **Mi primer censo clasificaba con")
a("una expresion regular** y daba ROJO sobre dos sitios que son DOCSTRINGS, no llamadas;")
a("se rehizo con `ast`. **Lo demas de ese tramo lo lei dos veces y no encontre nada")
a("mas:** la formula canonica falla ruidoso en los tres extremos y el giro recoge sus")
a("fallos, igual que decia el reporte de la 144.")
a("")
a("**2.a. EL ANCLA UNICA, EN LOS TRES PARES DE MARCAS.** `quitar_bloques_cubiertos()`")
a("aprende una **CUARTA regla de delimitador**, que va ANTES que las otras tres y no")
a("cambia ninguna: **si cualquiera de las seis marcas aparece mas de una vez, es ROJO POR")
a("AMBIGUA**, nombrando la marca y **todas** sus posiciones. No se toma la primera. Las")
a("cuatro mutaciones, con sujeto congelado por ref de git y veredicto por computo:")
a("")
a("```")
a(leer("SALIDA_V145_2A_MUTACION_ANCLA_UNICA.txt", desde="ELECCION DEL SUJETO POR COMPUTO",
       hasta="(i) EL SUJETO TAL CUAL"))
a(leer("SALIDA_V145_2A_MUTACION_ANCLA_UNICA.txt", desde="  (i) marca de COBERTURA"))
a("```")
a("Contado de `SALIDA_V145_2A_MUTACION_ANCLA_UNICA.txt`.")
a("")
a("La `(i)` trae el contraste que hace que la mutacion valga: **con el codigo de ayer el")
a("mismo sujeto sale VERDE y en silencio**; con la regla nueva sale ROJO nombrando la")
a("marca. La `(ii)` prueba que **la regla no cambia lo que se mide**, solo cuando se")
a("niega a medir: quitado el segundo par, VERDE y **la misma cuenta de ayer**.")
a("")
a("**2.b. LOS CUATRO ARNESES, CURADOS DEL SUJETO VIVO.**")
a("")
a("| arnes | que se hizo | antes | despues |")
a("|---|---|---|---|")
a("| `vuelta144_2d_mutacion_cobertura.py` | sujeto CONGELADO y commiteado, elegido por computo | 1 de 3 | **3 de 3** |")
a("| `vuelta144_3b_mutacion_negativa.py` | PRE-ESTADO congelado por ref de git computado | 1 de 3 | **3 de 3** |")
a("| `vuelta144_2a_guarda_semantica.py` | acepta DOS refs, invocacion canonica en el docstring | ROJO | **VERDE** |")
a("| `vuelta144_3b_guarda_semantica.py` | acepta DOS refs, invocacion canonica en el docstring | ROJO | **VERDE** |")
a("")
a("**ELEGI CONGELAR Y NO DECLARAR EN LOS DOS PRIMEROS, Y EL MOTIVO ES MEDIDO:** un CASO")
a("DECLARADO deja el arnes **excusado y sin morder**; congelado vuelve a **3 de 3** en")
a("los dos. Para el negativo de la 3.b el ref **se computa, no se teclea**: se busca el")
a("commit mas nuevo que deja deprecado al absorbido y se toma **su padre**. Los dos")
a("absorbidos dan el mismo, `5fff85f7`, deprecados los dos en `c72ce2c0`; si dieran refs")
a("distintos es ROJO PREVIO y no se elige uno.")
a("")
a("**Y LA MITAD QUE FALTABA: UN ARNES CONGELADO QUE YA NO MUERDE ES PEOR QUE UNO ROJO.**")
a("Se relajo **la guarda que cada uno prueba** (no el arnes, no su sujeto) y se exigio")
a("que el arnes CAYERA, y luego que volviera a verde con la guarda entera:")
a("")
a("```")
a(leer("SALIDA_V145_2B_MUTACION_ARNESES.txt", desde="ARNES vuelta144_2d"))
a("```")
a("Contado de `SALIDA_V145_2B_MUTACION_ARNESES.txt`.")
a("")
a("**Y ENTRAN EN `VIEJAS`, por la regla**, las tres que nacieron en la TAREA 3 de la 144")
a("y **las tres que escribi hoy**. La bateria pasa de trece a diecinueve entradas.")
a("")
a("**2.c. EL CENSO COMPLETO, IMPRESO POR UN INSTRUMENTO Y CON LOS NUMEROS DE LINEA DE")
a("HOY.** `scripts/loop/vuelta145_2c_censo_de_llamadas.py`, pegado entero:")
a("")
a("```")
a(leer("SALIDA_V145_2C_CENSO_DE_LLAMADAS.txt", desde="FICHERO", hasta="CIFRA ficheros"))
a("```")
a("Contado de `SALIDA_V145_2C_CENSO_DE_LLAMADAS.txt`.")
a("")
solo_lineas(P, "SALIDA_V145_2C_CENSO_DE_LLAMADAS.txt", "CIFRA ")
a("```")
a(leer("SALIDA_V145_2C_CENSO_DE_LLAMADAS.txt", desde="FICHEROS QUE SOLO LO MENCIONAN",
       hasta="EXITCODE"))
a("```")
a("Contado de `SALIDA_V145_2C_CENSO_DE_LLAMADAS.txt`.")
a("")
a("**MI CENSO DIFIERE DEL DEL ACTA EN LA UNIDAD, Y LO DECLARO EN VEZ DE COPIARLO.** El")
a("acta dice *llamadas en OCHO ficheros*. Medido hoy con `ast` y no con una expresion")
a("regular, la cuenta de ficheros con una LLAMADA de verdad **cuadra con la del acta**, y")
a("la de ficheros donde el nombre solo APARECE es mayor.")
a("`vuelta144_1b_medir_ventana.py` **solo lo menciona en prosa y no lo llama**, y los")
a("demas de mas son instrumentos que nacieron HOY. **La diferencia es de unidad, no de")
a("fondo: las dos llamadas que el acta nombra como culpables existen y estaban donde")
a("dice.**")
a("")
a("**LAS DOS QUE TIRABAN SUS FALLOS, REPARADAS**, y la tercera, la de la contraprueba del")
a("codigo viejo, **se queda como esta y ahora lo DECLARA en su propia linea**. La")
a("mutacion:")
a("")
a("```")
a(leer("SALIDA_V145_2C_MUTACION_CENSO.txt", desde="FICHA ROTA POR COMPUTO", hasta="====="))
a("```")
a("Contado de `SALIDA_V145_2C_MUTACION_CENSO.txt`.")
a("")
a("**2.d. EL INSTRUMENTO DE LA 3.d, COMMITEADO, CON SU UNIDAD BIEN NOMBRADA.**")
a("`scripts/loop/vuelta145_2d_aristas_movidas.py`:")
a("")
a("```")
a(leer("SALIDA_V145_2D_ARISTAS_MOVIDAS.txt", desde="LAS DOS UNIDADES", hasta="ENTRAN ("))
a(leer("SALIDA_V145_2D_ARISTAS_MOVIDAS.txt", desde="LOS MISMOS CONJUNTOS", hasta="ADJUDICACION"))
a("```")
a("Contado de `SALIDA_V145_2D_ARISTAS_MOVIDAS.txt`.")
a("")
a("**MI MEDICION Y LA DEL AUDITOR COINCIDEN AL DIGITO EN LAS CUATRO CIFRAS**, y ademas la")
a("diferencia entre las dos unidades es la que el acta dice. **PERO LA UNIDAD (A) NO ES")
a("LA QUE EL ACTA LE PONE DE NOMBRE, Y ESO LO TRAIGO YO:** el acta la llama *aristas")
a("resueltas con la FUENTE viva*; medido, esa definicion da **7.327 y 7.325**, no las")
a("publicadas. Probe las seis variantes posibles sobre los mismos dos commits y **solo")
a("una reproduce las cifras publicadas: la UNION DE LAS DOS VISTAS leidas de nodos")
a("vivos**. Las cifras del acta y del reporte de la 144 son ciertas; **el nombre de su")
a("unidad, en las DOS, no lo era**, y el instrumento commiteado lleva ahora el nombre")
a("medido.")
a("")
a("**2.e. LA FRONTERA DE LOS DOS SELLADORES, ESCRITA** en el docstring de")
a("`generar_plan_de_fusion_de_mesa.py` y en el de `vuelta144_3b_sellar_mesa_opm04.py`,")
a("**sin tocar el codigo de ninguno**: el de la casa sella **UNA fusion con UN")
a("superviviente**, el nuevo sella **UNA MESA DE DOS ACTOS**, y **quien decide cual se")
a("usa es la figura que la ficha declara en su propio `tipo`**, no el gusto de quien")
a("sella.")
a("")
a("**AL CERRAR LA TAREA 2**, el ciclo de Gate 0 con las suites detras. Numstat del ciclo,")
a("de `SALIDA_V145_2_CICLO_NUMSTAT.txt`: **ni una fila** (solo el aviso de finales de")
a("linea de git). Motor **25/25**, vitest **verde**, tsc **EXITCODE 0 sin salida**. Y la")
a("bateria:")
a("")
a("```")
a(leer("SALIDA_V145_2_VIEJAS_TRAS_TAREA2.txt", desde="  ANCLA PERDIDA", hasta="      vuelta135_2e"))
a("```")
a("Contado de `SALIDA_V145_2_VIEJAS_TRAS_TAREA2.txt`.")
a("")
a("## 3. LA APERTURA DE LA FASE 07 ADUANA")
a("")
a("**3.a. LEIDO ENTERO ANTES DE TOCAR NADA**: las fichas de `OP-A-01` y `OP-A-02`,")
a("`docs/plan/07_ADUANA.md` entero, y el precedente de la fase 05. **EL PRECEDENTE SIRVE,")
a("PERO SOLO PARA LA MITAD, Y LO DECLARO.** Medido por mi con")
a("`tallar_estado_de_fase.py --fase 05_SANEO`:")
a("")
a("```")
a(leer("SALIDA_V145_3A_ESTADO_FASE05_PRECEDENTE.txt", desde="CIFRA:", hasta="CONSUMIDAS CON"))
a("```")
a("Contado de `SALIDA_V145_3A_ESTADO_FASE05_PRECEDENTE.txt`.")
a("")
a("**SIRVE** para lo que importa hoy: **una operacion sin vara de grafo no bloquea la")
a("fase**, y hay camino andado. **NO SIRVE** como metodo de certificacion: esas nueve")
a("descansan en su campo `estado`, que las actas 139 a 144 congelan y **que ninguna cifra")
a("mira**, y ademas `OP-S-12` **sigue en LISTA**. O sea que el precedente da permiso para")
a("seguir, **no una vara**. La vara la da la adjudicacion 3.9, y es la 3.b.")
a("")
a("**3.b. LA VARA DE CODIGO, EN INSTRUMENTO APARTE Y CON SU FRONTERA.**")
a("`scripts/loop/vuelta145_3b_vara_de_codigo_fase07.py` mide **dos cosas y solo dos** por")
a("control: **que exista en el codigo** y **que muerda por mutacion**. **CADA CONTROL")
a("LLEVA SU FRASE LITERAL DE LA FICHA Y LA CITA SE COMPRUEBA**, como se hizo con la")
a("figura de `OP-M-04`: si una ficha se reescribe y la cita deja de aparecer VERBATIM,")
a("**la vara se para y lo nombra** en vez de seguir midiendo con una cita muerta. El")
a("recuento:")
a("")
a("```")
a(leer("SALIDA_V145_3B_VARA_FASE07.txt", desde="EL RECUENTO, POR OPERACION",
       hasta="VEREDICTO DE LA FASE 07"))
a("```")
a("Contado de `SALIDA_V145_3B_VARA_FASE07.txt`.")
a("")
a("**LA FRONTERA SE CUMPLE Y SE MIDE:** el puntero al instrumento nuevo va **en el")
a("docstring** de `tallar_estado_de_fase.py`, **no en una columna**. Corrida la tabla")
a("antes y despues del puntero, **sale IDENTICA linea por linea**, y las dos operaciones")
a("siguen diciendo **SIN VARA ESCRITA** y **NO COMPUTABLE**, que es la verdad medida")
a("contra el grafo:")
a("")
a("```")
a(leer("SALIDA_V145_3B_ESTADO_FASE07_TRAS_PUNTERO.txt", desde="CIFRA:", hasta="CONSUMIDAS CON"))
a("```")
a("Contado de `SALIDA_V145_3B_ESTADO_FASE07_TRAS_PUNTERO.txt`.")
a("")
a("**Y LA FASE 06 NO SE MUEVE**, comprobado en esta misma vuelta:")
a("")
a("```")
a(leer("SALIDA_V145_3_ESTADO_FASE06_CONTRASTE.txt", desde="CIFRA:", hasta="CONSUMIDAS CON"))
a("```")
a("Contado de `SALIDA_V145_3_ESTADO_FASE06_CONTRASTE.txt`.")
a("")
a("**3.c. EL PRERREQUISITO DE `OP-A-01`: NO ESTA CUMPLIDO, Y ESE ES EL BLOQUEO")
a("NOMBRADO.** Medido hoy contra el grafo con instrumento propio")
a("(`scripts/loop/vuelta145_3c_prerrequisito_op_a_01.py`). Las cifras, pegadas de su")
a("salida:")
a("")
solo_lineas(P, "SALIDA_V145_3C_PRERREQUISITO.txt", "CIFRA ")
a("El detalle grafia por grafia, con cuantos nodos usa cada una, vive entero en")
a("`SALIDA_V145_3C_PRERREQUISITO.txt`, que es el fichero del que salen estas lineas.")
a("")
a("```")
a(leer("SALIDA_V145_3C_PRERREQUISITO.txt", desde="(4) LA DECLARACION", hasta="EXITCODE"))
a("```")
a("Contado de `SALIDA_V145_3C_PRERREQUISITO.txt`.")
a("")
a("**TRES COSAS QUE TRAIGO Y NO RESUELVO COPIANDO.** (1) El campo `fuente` **es UNA SOLA")
a("CADENA por nodo** (medido: en el grafo entero son todas `str`, ni una lista), y el")
a("separador real del catalogo es la barra vertical; se publica ademas la cuenta con")
a("punto y coma **para que se vea que no se esta contando un separador de AUTORES como si")
a("fuera de LIBROS** (el caso vivo: *Deming, W. Edwards; Cahill, Kev*, dos autores del")
a("mismo libro). (2) **Las cifras de la ficha llevan corte del 11 ago 2026 y hoy no se")
a("reproducen**, ni la de nodos con mas de un libro ni la de declaraciones en segunda")
a("posicion, y **no puedo re-correr su instrumento porque no esta en `scripts/`**, asi")
a("que declaro la discrepancia en vez de explicarla. (3) **Las grafias piden decir su")
a("unidad, y aqui es justo la caida 4.7 otra vez**: entre vivos, Hugos y Horowitz tienen")
a("UNA grafia cada uno; contando todos los nodos, DOS cada uno. **La 'DOS grafias de")
a("Hugos' de la ficha REPRODUCE contando todos los nodos; la 'TRES de Horowitz' da DOS.**")
a("En las dos, **la grafia vieja vive hoy solo del lado deprecado**, o sea que el sintoma")
a("**es real y sigue entrando por la puerta que la aduana vigila**.")
a("")
a("**LA DECLARACION:** no existe en el repositorio **ninguna** lista canonica de libros")
a("con sus alias (buscados tres nombres candidatos, ninguno existe), y su dueno")
a("`OP-S-11` **sigue SIN VARA ESCRITA en la fase 05**. **NO IMPROVISO LA LISTA.** La fase")
a("07 queda **ABIERTA Y MEDIDA con su bloqueo nombrado**, que es el encargo; cerrarla no")
a("lo es.")
a("")
a("**3.d. NINGUNA ARISTA SE MOVIO, ASI QUE NO HAY NADA QUE PARAR.** La condicion sigue")
a("viva y no se disparo: esta vuelta **no ejecuta ninguna operacion** y **no escribe ni")
a("retira una sola flecha**. Medido: el censo de apertura y el de cierre dan las mismas")
a("cuatro cuentas, la fila de aristas movidas de la cabecera tallada dice **+0 / +0 / +0")
a("/ +0**, y el numstat del ciclo no trae una fila.")
a("")
a("**3.e. NINGUNA DE LAS DOS OPERACIONES SE EJECUTO**, y el campo `estado` **sigue sin")
a("tocarse**, incluido el pase del par 1190 fuera de congelados, que **mide bien pero NO")
a("se aplica**: va en una sola adjudicacion del auditor con el conteo antes y despues, y")
a("no es esta. `OP-S-12` sigue al final de la pasada entera.")
a("")
a("## 4. EL CIERRE")
a("")
a("**4.a.** Los diez nombres canonicos del lado CIERRE, con `SALIDA_V145_HEAD_CIERRE.txt`")
a("sellado tras la ultima operacion y antes de escribir el hash aqui. **4.b.** La")
a("cabecera tallada y pegada entera arriba, con `--comparar` y `--comparar-commits`")
a("corridos. **4.c.** La guarda de cifras corrida sobre este mismo reporte, con su linea")
a("de cobertura pegada UNA SOLA VEZ y vuelta a correr despues de pegarla. **4.d.** La")
a("bateria `VIEJAS` re-corrida DESPUES de escribir el reporte y ANTES del commit final.")
a("")
a("**UNA REPARACION MAS, HALLADA AL CORRER LA 4.c Y NO ESCONDIDA.** La guarda de cifras")
a("**reventaba con una traza de pila** al leer un fichero de salida citado que no es")
a("UTF-8: `SALIDA_V145_CICLO_ETIQUETAS_APERTURA.txt` se captura con la codificacion de la")
a("consola de Windows, y **lleva asi desde al menos la vuelta 144** (medido: el fichero")
a("de la 144 tampoco decodifica). Nadie lo habia visto porque **hasta hoy ningun reporte")
a("lo habia CITADO**. Reparado: se decodifica con reemplazo, **y la linea de cobertura")
a("publica ahora los ficheros citados que no son UTF-8, con su nombre**. Ninguna de las")
a("cuatro unidades que la guarda cuenta depende de un acento, pero **callarlo seria la")
a("degradacion silenciosa que el banco 9 prohibe**.")
a("")
a("**LA PAREJA DE MARCAS DE COBERTURA APARECE EXACTAMENTE UNA VEZ EN ESTE FICHERO**, por")
a("la regla nueva de la 4.c; donde hace falta citar el mecanismo en prosa lo cito por su")
a("nombre en castellano y **nunca con el literal de verdad**, que es justo lo que la 2.a")
a("de esta vuelta convierte en ROJO.")
a("")
a("**4.b, LAS DOS COMPARACIONES, PEGADAS.** `--fase04 --comparar docs/loop/REPORTE.md`:")
a("")
a("```")
a(leer("SALIDA_V145_4B_COMPARAR_CABECERA.txt", desde="  filas cotejadas", hasta="FIN"))
a("```")
a("Contado de `SALIDA_V145_4B_COMPARAR_CABECERA.txt`.")
a("")
a("Y `--comparar-commits docs/loop/REPORTE.md`, que se ancla al HEAD sellado de cierre y")
a("por eso se corre DESPUES de commitear el bloque de cierre:")
a("")
a("```")
a(leer("SALIDA_V145_4B_COMPARAR_COMMITS.txt", desde="  commits en el bloque del fichero",
       hasta="EXITCODE"))
a("```")
a("Contado de `SALIDA_V145_4B_COMPARAR_COMMITS.txt`.")
a("")
a("**4.d, EL PASO NUEVO Y BLOQUEANTE, CORRIDO DESPUES DE ESCRIBIR ESTE REPORTE Y ANTES")
a("DEL COMMIT FINAL.** Es la reparacion de la caida 4.8 del acta: sin el, el verde de una")
a("vuelta no puede sobrevivir a la vuelta, porque la bateria tiene un miembro cuyo sujeto")
a("era el propio reporte. Corrido SOBRE EL FICHERO QUE SE VA A COMMITEAR:")
a("")
a("```")
a(leer("SALIDA_V145_4D_VIEJAS_TRAS_REPORTE.txt", desde="  ANCLA PERDIDA",
       hasta="      vuelta135_2e"))
a("```")
a("Contado de `SALIDA_V145_4D_VIEJAS_TRAS_REPORTE.txt`.")
a("")
a("**VERDE, CON NO MORDIO EN CERO.** El arnes que la vuelta 144 envio en rojo ya no toma")
a("el reporte vivo como sujeto, asi que escribir este reporte no lo tumba.")
a("")
a("<!-- COBERTURA DE LA GUARDA -->")
a("```")
a("PENDIENTE_COBERTURA")
a("```")
a("<!-- FIN COBERTURA DE LA GUARDA -->")
a("")
a("## LOS DISCUTIBLES, MARCADOS ANTES DE SABER SI ACIERTO")
a("")
a("**DISCUTIBLE 1. CONGELE EL PRE-ESTADO POR REF DE GIT EN VEZ DE COMMITEAR UN SUJETO.**")
a("El encargo dice *un SUJETO CONGELADO commiteado en `docs/loop/`* y el patron que cita")
a("es un fichero. Para el negativo de la 3.b **no commitee un fichero: monto el")
a("pre-estado desde un ref de git en un temporal**. Mi motivo: los sujetos de ese caso")
a("son **nodos del catalogo** y `OPERACIONES.jsonl`, y una copia commiteada de un nodo")
a("seria **un segundo nodo con el mismo id**. **Es una desviacion de la letra del encargo")
a("y va marcada la primera.**")
a("")
a("**DISCUTIBLE 2. REUSE EL SUJETO CONGELADO DE LA VUELTA 135 EN VEZ DE CREAR UNO.** Para")
a("el arnes de cobertura, el candidato elegido por computo es")
a("`SUJETO_FIJO_V135_2E_REPORTE_134.md`, que ya existe y ya lo cotejan las mutaciones de")
a("la 135. **Gano reuso y pierdo independencia**: si alguien tocara ese fichero, caerian")
a("dos arneses a la vez en vez de uno.")
a("")
a("**DISCUTIBLE 3. LA CUARTA REGLA LEVANTA `ValueError` Y NO ANADE UN FALLO A LA LISTA.**")
a("Segui el patron que la funcion ya tenia para *una sola marca*, asi que el rojo llega")
a("como traza y no como fallo numerado. **Es consistente con lo que habia, pero es una")
a("decision y no una obligacion.**")
a("")
a("**DISCUTIBLE 4. NOMBRO TODAS LAS MARCAS REPETIDAS DE UNA CORRIDA, NO SOLO LA")
a("PRIMERA.** El encargo dice *nombrando la marca y sus posiciones*, en singular. Doy")
a("mas: **todas las repetidas a la vez**, para no obligar a correr la guarda en bucle.")
a("")
a("**DISCUTIBLE 5. MI CENSO PARTE LA UNIDAD EN DOS COLUMNAS Y NO DA UN SOLO NUMERO.** Con")
a("`ast`, `vuelta144_1b_medir_ventana.py` **solo menciona** el nombre. Publico APARICION y")
a("LLAMADA por separado. **Podria leerse como que discuto la caida 4.1: no la discuto, la")
a("acepto entera**; lo que separo es la unidad.")
a("")
a("**DISCUTIBLE 6. REHICE MI PROPIO INSTRUMENTO DENTRO DE LA MISMA VUELTA Y LO DECLARE EN")
a("SU DOCSTRING.** El censo nacio con expresion regular, se delato solo con dos falsos")
a("rojos y lo rehice con `ast`. **Deje escrito el defecto viejo en vez de borrarlo**, y")
a("puede parecer ruido en un fichero que nace hoy.")
a("")
a("**DISCUTIBLE 7. LE PUSE A LA UNIDAD (A) UN NOMBRE DISTINTO DEL QUE EL ACTA LE DA.** El")
a("acta la llama *con la FUENTE viva*; medido, eso da otras dos cifras. **Cambio el")
a("nombre porque la definicion que reproduce las cifras publicadas es la union de las dos")
a("vistas**, y publico las variantes que probe. **Es corregir al auditor en un rotulo, y")
a("va marcado.**")
a("")
a("**DISCUTIBLE 8. LA VARA DE LA FASE 07 MIDE NUEVE CONTROLES Y EL ENCARGO NOMBRA CINCO")
a("PARA `OP-A-01`.** Leidas las fichas, **los cinco controles mecanicos los nombra")
a("`OP-A-02` en su `verificacion`, no `OP-A-01`**, que nombra tres cosas propias. **Medi")
a("el superconjunto**: los tres de `OP-A-01`, los cinco de `OP-A-02` y el bloqueo por")
a("veredicto ausente. **No pierdo nada y cubro las dos lecturas, pero no es literalmente")
a("el reparto que el encargo describe.**")
a("")
a("**DISCUTIBLE 9. LAS SONDAS DE 'EXISTE EN EL CODIGO' SON LITERALES QUE ELEGI YO.** Un")
a("control podria estar instalado con otras palabras y mi vara diria NO INSTALADO. Lo")
a("mitigo publicando **el fichero y la linea de cada hallazgo, y el literal exacto que")
a("busque cuando no lo encuentro**, para que la sonda se pueda discutir; pero **la")
a("eleccion del literal es mia**.")
a("")
a("**DISCUTIBLE 10. DI POR NO CUMPLIDO EL PRERREQUISITO MIRANDO TRES NOMBRES DE FICHERO.**")
a("Busque tres rutas candidatas de lista canonica. **Una busqueda negativa no se puede")
a("citar** (`EJECUTOR.md` 9), asi que lo apoyo ademas en algo positivo: **la grafia vieja")
a("de los dos libros existe hoy en el catalogo**, del lado deprecado, o sea que **nada la")
a("esta normalizando**.")
a("")
a("**DISCUTIBLE 11. TOQUE LA GUARDA DE CIFRAS DESPUES DE CERRAR LA TAREA 2.** La")
a("reparacion del fichero citado que no es UTF-8 la hice **al correr la 4.c**, con el")
a("ciclo de la TAREA 2 ya verde. **Lo alternativo era no poder entregar la 4.c**, o quitar")
a("del reporte la cita que la destapa, que seria esconderla.")
a("")
a("**DISCUTIBLE 12. LA PROSA DE ESTE REPORTE EVITA REPETIR CIFRAS SUELTAS.** Las cifras")
a("viven dentro de los bloques pegados, con su fichero debajo. **Se lee peor y se cuenta")
a("mejor**: una cifra en prosa lejos de su instrumento es exactamente lo que la guarda")
a("declara incontable, y prefiero un reporte mas seco a uno con cifras que nadie puede")
a("cotejar.")
a("")
a("## PREGUNTAS")
a("")
a("**PREGUNTA 1.** La ficha de `OP-A-01` publica cifras con corte del **11 ago 2026** que")
a("**hoy no se reproducen**, y **su instrumento no esta en `scripts/`**. No toque la")
a("ficha. **Se re-mide y se corrige su `evidencia` por adicion declarada, o se deja como")
a("cifra historica con su corte?** No lo adivino.")
a("")
a("**PREGUNTA 2.** La vara de la 3.b dice que **tres de los nueve controles ya estan")
a("instalados y muerden**, y los tres viven en Gate 0, **no en una aduana**. **Cuenta eso")
a("como control de entrada de `OP-A-02` cumplido, o la aduana exige un punto de insercion")
a("propio aunque el control ya exista y muerda?** La ficha dice *los CINCO controles")
a("mecanicos corriendo* y no dice DONDE.")
a("")

texto = "\n".join(P) + "\n"
io.open(os.path.join(LOOP, "REPORTE.md"), "w", encoding="utf-8", newline="\n").write(texto)
print("escrito docs/loop/REPORTE.md, %d lineas" % len(texto.split("\n")))
