# -*- coding: utf-8 -*-
# constructor del lote del tramo. escribe docs/loop/_lote.jsonl con {puesto,clase,razon}.
# SOLO arma texto; el registro lo hace registrar_veredictos.py.
import json, io, sys
lote = []
def add(p, c, r):
    assert "—" not in r and "–" not in r, "guion largo en %d" % p
    lote.append({"puesto": p, "clase": c, "razon": r})

# ================= TRAMO 2801-2825 =================
add(2801, "D",
 "adopcion_liderazgo (Adoptar e Instituir el Liderazgo, Punto 7 de Deming: dejar de evaluar solo "
 "con metas numericas, aprender a fondo el trabajo antes de dirigir, corregir las condiciones que "
 "lo dificultan, usar datos para ver que esta fuera de linea) contra aim_of_leadership (Objetivo "
 "del Liderazgo: identificar con datos quien esta fuera de lo esperado por bajo o muy alto, "
 "investigar causas de sistema, disenar ayuda o reconocimiento, mejorar el sistema para todos, "
 "estudiar a los excepcionales para replicar sus metodos, reducir la variabilidad entre personas). "
 "MISMA FUENTE Deming, sin arista, sim_tit 49,3. Comparten un paso (usar datos para hallar quien "
 "esta fuera de linea, no solo bajo el promedio), pero cada uno trae pasos enteros propios: "
 "adopcion tiene dejar de evaluar con cifras y aprender el trabajo antes de delegar; aim tiene "
 "estudiar a los excepcionales para replicar y reducir la variabilidad entre personas. Instituir "
 "el liderazgo no es el objetivo del liderazgo: uno es la practica, el otro su proposito. Ninguno "
 "cabe entero en el otro. D. DISCUTIBLE MARCADO: comparten el foco en el sistema no la persona; "
 "quien pese ese nucleo dira A.")
add(2802, "D",
 "calculo_roi_calidad (Calculo del ROI en Calidad: pedir ayuda de finanzas, diferenciar capital de "
 "operativo, estimar rapido por muestreo en vez de expandir la contabilidad, validar que la "
 "decision no cambie ante un rango de estimaciones) contra roi_breakthrough (ROI de Proyectos de "
 "Breakthrough: calcular costo de diagnostico y remedio, compararlo con el ahorro por reducir "
 "desperdicio cronico, documentar el ROI para la direccion, usar casos de exito como Samsung Six "
 "Sigma para justificar seguir invirtiendo). MISMA FUENTE Juran, sin arista, sim_tit 65,4. "
 "TRANSITIVIDAD DEL CUMULO: roi_proyectos_calidad =D= calculo_roi_calidad (2427) y "
 "roi_proyectos_calidad =A= roi_breakthrough (2451), asi que calculo y breakthrough caen a lados "
 "distintos: D. El contenido lo confirma: uno es la mecanica contable del ROI (capital vs "
 "operativo, muestreo, sensibilidad), el otro la justificacion de un proyecto de mejora (costo de "
 "diagnostico contra ahorro cronico, benchmark para la direccion). D. DISCUTIBLE MARCADO: ambos "
 "calculan un ROI de calidad; quien pese ese nucleo dira A.")
add(2803, "D",
 "clasificacion_de_seriedad_de_defectos (Clasificacion de Seriedad y Demeritos por Unidad: definir "
 "categorias, asignar peso de demerito, registrar defectos por categoria, calcular demeritos "
 "totales por unidad, usar el indice para comparar tendencias y competencia) contra "
 "clasificacion_seriedad (Seriousness Classification: reunir a los pocos que ayudan, decidir "
 "cuantos niveles tres o cuatro, definir cada nivel con criterios, clasificar cada caracteristica "
 "y defecto, usar la clasificacion para planificar inspecciones y especificaciones). MISMA FUENTE "
 "Juran, sim_tit 54,4. El primero CALCULA el indice de demeritos (una metrica ponderada por "
 "unidad para comparar tendencias); el segundo MONTA el esquema de niveles de gravedad y clasifica "
 "las caracteristicas. Disenar la escala no es calcular el indice. Familia toda D: 2540, 2589 "
 "(este nodo contra sus hermanos), 2476, 2570 (el otro contra los suyos), 2429 y 2439; el cumulo "
 "de la clasificacion de seriedad separa cada variante. D. DISCUTIBLE MARCADO: comparten la "
 "seriedad del defecto como eje; quien lo pese dira A.")
add(2804, "D",
 "herramientas_de_diseno_de_calidad (Herramientas Frecuentes de Diseno de Calidad: seleccionar la "
 "herramienta segun la fase, afinidad o lluvia de ideas para agrupar, FMEA y arbol de fallas para "
 "priorizar riesgos, hojas de calculo de necesidades y de diseno de producto) contra "
 "spreadsheet_diseno_para_la_calidad (Hojas de calculo de Diseno para la Calidad QFD: hoja de "
 "necesidades del cliente, desglose de general a particular, hoja de diseno de producto que vincula "
 "necesidad con caracteristica, extension a diseno y control de proceso). MISMA FUENTE Juran, "
 "sim_tit 52,2. FICHA CONTRA MAPA: el primero es el MENU de herramientas de diseno (afinidad, "
 "FMEA, arbol de fallas, hojas de calculo) y solo NOMBRA la hoja de calculo como una de ellas; el "
 "segundo ES esa hoja desplegada entera. La familia lo confirma: spreadsheet =A= qfd_matriz (2469) "
 "pero =D= customer_needs_spreadsheet (2693) y =D= product_design_spreadsheet (2425), o sea es una "
 "hoja concreta, no el menu. El menu tiene FMEA y arbol de fallas que la hoja no trae. D. "
 "DISCUTIBLE MARCADO: la hoja aparece nombrada en el menu; quien lea eso como contencion dira A.")
add(2805, "A",
 "accion_correctiva_crosby (Accion Correctiva Sistematica: investigar causa raiz consultando al "
 "operativo, auditorias independientes por departamento, documentar en reportes formales de "
 "ingenieria de calidad, planes de accion por departamento) contra accion_correctiva_sistematica "
 "(Accion Correctiva Sistematica, Paso 6 de Crosby: ficha por problema con que paso y quien "
 "responde, revision diaria, escalar a semanal y mensual lo sin resolver, grupo de trabajo para "
 "los complejos, atacar por gravedad). MISMA FUENTE Crosby, mismo titulo, sin arista, sim_tit "
 "75,3. Es el Paso 6 de Crosby descrito dos veces: uno acentua la estructura (auditorias, "
 "reportes, responsables por departamento), el otro la cadencia (diaria, semanal, mensual, grupo, "
 "gravedad). A POR TRANSITIVIDAD DEL CUMULO: accion_correctiva_crosby =A= accion_correctiva_6 "
 "(2426) y accion_correctiva_sistematica =A= accion_correctiva_6 (2701), asi que fusionan entre "
 "si. A, superviviente POR ELEGIR. DISCUTIBLE MARCADO fuerte: el cumulo no es limpio, crosby =D= "
 "accion_correctiva_5 (2496) mientras sistematica =A= accion_correctiva_5 (2431); quien pese esa "
 "grieta y lea la estructura como cara distinta de la cadencia dira D.")
add(2806, "D",
 "cinco_suposiciones_erroneas_calidad (Las Cinco Suposiciones Erroneas sobre la Calidad, Crosby: "
 "revisar cuales estan presentes, aprender la definicion correcta y medirla por costos, buscar el "
 "origen real de los defectos no solo en quien produce, redefinir el rol de quien revisa la "
 "calidad) contra mito_departamento_control_calidad (el mito de delegar por completo la calidad, "
 "Deming: redefinir el rol del de calidad como asesor no unico responsable, involucrarte en las "
 "decisiones, pedir reportes de estabilidad del proceso, liderar la mejora como aprendizaje "
 "continuo). FUENTES DISTINTAS Crosby y Deming, sim_tit 41,8. Comparten un tema, redefinir el rol "
 "del de calidad, pero el primero es un marco de CINCO suposiciones (definicion, costo, "
 "inevitabilidad, origen, rol) y el segundo elabora SOLO el mito de la delegacion con pasos "
 "propios (involucrarte, pedir reportes de estabilidad, liderar). El marco de cinco no cabe en el "
 "mito ni el mito en el marco. D. DISCUTIBLE MARCADO: el mito es una de las cinco suposiciones; "
 "quien lea ficha contra mapa a favor de contencion dira A.")
add(2807, "D",
 "ingenieria_calidad (Ingenieria de Calidad, Crosby: definir con quien disena las caracteristicas "
 "del producto nuevo, coordinar el metodo de produccion y los puntos de control, detallar que "
 "inspeccionar y capacitar a quien ejecuta, fijar metricas y frecuencia) contra "
 "sistema_gestion_calidad (Sistema de Gestion de Calidad, Juran: mapear todos los procesos que "
 "afectan la calidad, identificar quien controla cada parte, coordinar entre partes, documentar el "
 "sistema segun los estandares del mercado). FUENTES DISTINTAS, sim_tit 64,0. Niveles distintos: "
 "el primero es la FUNCION operativa de ingenieria de calidad de un producto o proceso; el segundo "
 "es el SISTEMA de gobierno de la calidad de todo el negocio (mapa de procesos, quien controla, "
 "documentacion). Familia D: ingenieria_calidad =D= planificacion_inicial_calidad (2611), =D= "
 "planificacion_de_la_inspeccion (2714), =D= funciones_del_departamento_de_calidad (2763); "
 "sistema_gestion_calidad =D= gestion_para_la_calidad (2683). D. DISCUTIBLE MARCADO: ambos "
 "coordinan calidad entre areas; quien pese ese nucleo dira A.")
add(2808, "D",
 "accion_correctiva_2 (De la Deteccion a la Prevencion, Crosby: observar rechazos reales como "
 "evidencia, analisis de tendencias para lo menos obvio, causa raiz sistemica no culpar, cambios "
 "que prevengan la recurrencia) contra accion_correctiva_6 (Destapar Causas, Rolling Over the "
 "Rocks: documentar via auditorias de calidad, investigar la causa raiz, asignar responsables y "
 "plazos, seguimiento hasta verificar que se elimino). MISMA FUENTE Crosby, sim_tit 52,3. Cada uno "
 "trae un paso entero propio: el 2 tiene el analisis de tendencias para detectar lo no obvio (el "
 "giro deteccion a prevencion); el 6 tiene la auditoria como fuente y la asignacion de responsable "
 "y plazo con verificacion. La familia lo respalda: accion_correctiva_6 vive en el cumulo A (2418, "
 "2426, 2701) pero accion_correctiva_2 quedo FUERA, sus dos veredictos son D (2689, 2788). El paso "
 "entero propio rompe la contencion (la vara del 2652). D. DISCUTIBLE MARCADO: comparten causa "
 "raiz sistemica y prevenir la recurrencia; quien pese ese nucleo dira A.")
add(2809, "D",
 "alineacion_estrategica_despliegue (Alineacion entre estrategia y metas de calidad, Juran: "
 "identificar mision y politicas, verificar coherencia largo contra corto plazo, revisar como se "
 "despliega el plan, detectar areas desalineadas, realinear iniciativas) contra "
 "consejo_ejecutivo_calidad (Crear un espacio de revision de calidad: definir quien participa, "
 "fijar la frecuencia, replicar en equipos si crece, asignar vigilar los KPI y ejecutar el plan, "
 "fomentar la colaboracion). MISMA FUENTE Juran, sim_tit 54,3. Uno es el PROCESO de alineacion "
 "estrategica (coherencia, deteccion de brechas, realineamiento); el otro es el ORGANO de gobierno "
 "(el consejo: quien, cuando, que vigila). Comparten ejecutar el plan estrategico pero como "
 "proceso contra cuerpo. Familia: alineacion quedo D contra todo el cumulo estrategico (2587, "
 "2607, 2712, 2770). D. DISCUTIBLE MARCADO: el consejo tambien despliega la estrategia; quien lea "
 "eso como el mismo acto dira A.")
add(2810, "D",
 "single_double_multiple_sampling (Muestreo Simple, Doble y Multiple: evaluar volumen y complejidad "
 "administrativa, elegir simple por sencillez o doble y multiple por menor costo promedio, "
 "verificar que la curva OC cumpla los riesgos) contra tipos_planes_muestreo_atributos_variables "
 "(Planes por Atributos y por Variables: ver si las caracteristicas son medibles o pasa no pasa, "
 "elegir variables por menor muestra o atributos por multiples caracteristicas, calcular tamano y "
 "criterios segun la norma). MISMA FUENTE Juran, con arista, sim_tit 46,9. Son DOS EJES DISTINTOS "
 "de clasificar un plan de muestreo: el primero por la estructura de numero de muestras (simple, "
 "doble, multiple), el segundo por el tipo de dato (atributos contra variables). Ninguno cabe en "
 "el otro, son elecciones complementarias. Coincide con el cumulo del muestreo que separa por "
 "faceta (2702, 2753 D). D. DISCUTIBLE MARCADO: ambos eligen un plan de muestreo con la curva OC "
 "de fondo; quien pese ese nucleo dira A.")
add(2811, "A",
 "juran_transformation_roadmap (Hoja de Ruta de Transformacion Juran, 5 Fases Decide Prepare "
 "Launch Expand Sustain: recopilar lealtad y COPQ, desplegar y elegir pilotos, lanzar con charter "
 "y revision, expandir unidad por unidad 3 a 5 anos, integrar y auditar) contra "
 "roadmap_despliegue_lean_six_sigma (Roadmap de Despliegue Lean Six Sigma, Decide Prepare Launch "
 "Expand Sustain: evaluar si Six Sigma encaja, elegir con quien capacitarte, pausar iniciativas, "
 "definir quien guia, capacitar la primera ola de Champions y Belts, ejecutar con mentoria, llevar "
 "a otras areas, comparar con clase mundial, revisiones regulares). MISMA FUENTE Juran, sin "
 "arista, sim_tit 34,7 solo por los titulos. Es EL MISMO ROADMAP DPLES: las cinco fases coinciden "
 "una a una y los actos calzan (Decide recopilar y evaluar, Prepare pilotos y lideres, Launch "
 "ejecutar los primeros, Expand a otras areas en anos, Sustain integrar y auditar). El segundo es "
 "el primero con pasos mas granulares y vocabulario Six Sigma, no una iniciativa distinta. A por "
 "equivalencia del roadmap. Ojo: juran_transformation_roadmap =D= sus fichas de fase (2678, 2707) "
 "y =D= modelo_transformacion_juran (2748, que es el modelo de cinco breakthroughs), pero ESTE es "
 "otro roadmap DPLES entero, no una fase ni el modelo. A. DISCUTIBLE MARCADO fuerte: uno se rotula "
 "transformacion Juran y el otro despliegue Lean Six Sigma; quien los lea como iniciativas "
 "distintas dira D.")
add(2812, "D",
 "modelo_transformacion_juran (Modelo de Transformacion de Juran, Cinco Breakthroughs: evaluar el "
 "estado en cada uno de los cinco, disenar metas para cerrar brechas, desplegar proyectos en todas "
 "las funciones, integrar los cinco en la planificacion estrategica) contra "
 "secuencia_universal_breakthrough (Secuencia Universal para el Breakthrough: establecer la "
 "creencia de que el cambio es factible, estudio de factibilidad con Pareto, crear brazo directivo "
 "y brazo diagnostico, recolectar y analizar hechos, gestionar la resistencia cultural, implantar "
 "controles para sostener). MISMA FUENTE Juran, sim_tit 48,4. Son DOS conceptos Juran distintos: "
 "el primero es el MODELO de los cinco breakthroughs (evaluar cinco dimensiones e integrarlas); el "
 "segundo es la SECUENCIA universal de un solo breakthrough (creencia, factibilidad, brazos "
 "directivo y diagnostico, resistencia, control). El modelo de cinco no es la secuencia de uno. "
 "Familia: modelo_transformacion_juran =D= juran_transformation_roadmap (2748); "
 "secuencia_universal_breakthrough =A= secuencia_universal_para_el_breakthrough (2781, su gemelo "
 "real). D. DISCUTIBLE MARCADO: ambos hablan de breakthrough con brazo directivo; quien pese ese "
 "vocabulario dira A.")
add(2813, "D",
 "desarrollar_caracteristicas_proceso (Desarrollar las Caracteristicas del Proceso: listar "
 "procesos capaces de generar cada caracteristica del producto, evaluar la capacidad actual, "
 "seleccionar el proceso optimo con justificacion, fijar metas de proceso) contra "
 "diseno_de_procesos_por_caracteristicas (Diseno de Procesos Basado en Caracteristicas y Metas: "
 "identificar recursos, construir la hoja de calculo de diseno de proceso que vincula "
 "caracteristica de proceso con meta de producto, verificar cobertura en los dos sentidos, "
 "confirmar la capacidad de los macroprocesos). MISMA FUENTE Juran, sim_tit 67,4. Dos pasos "
 "distintos del cascadeo de diseno: el primero SELECCIONA el proceso (candidatos, capacidad, "
 "optimo, metas); el segundo construye la HOJA de diseno de proceso con recursos y verificacion "
 "bidireccional. Seleccionar el proceso no es armar la matriz de diseno. Familia del cascadeo toda "
 "D (2481, 2725). D. DISCUTIBLE MARCADO: ambos alinean caracteristica de proceso con meta de "
 "producto; quien pese ese nucleo compartido dira A.")
add(2814, "D",
 "falacia_culpa_trabajadores (La falacia de culpar solo a los trabajadores, Deming: analizar que "
 "porcentaje de defectos es del sistema contra quien ejecuta, revisar diseno, especificaciones, "
 "materiales y mantenimiento antes de culpar, meterte tu a mejorar el sistema, eliminar la idea de "
 "que el esfuerzo resuelve lo estructural) contra sistema_responsabilidad_gerencial (El Sistema es "
 "tu Responsabilidad: mapear los componentes del sistema, ver que esta bajo tu control, evaluar si "
 "el sistema permitia trabajar bien antes de culpar, rediseñar procesos en vez de corregir "
 "personas, escuchar advertencias tempranas). MISMA FUENTE Deming, sim_tit 36,6. Dos facetas del "
 "cumulo de la responsabilidad gerencial (POR ELEGIR provisional): la falacia es el DIAGNOSTICO "
 "(medir sistema contra persona, revisar las causas fisicas); el sistema es tu responsabilidad es "
 "la PROPIEDAD (mapear, rediseñar, escuchar). Todo el cumulo salio D entre sus variantes (2422, "
 "2443, 2619, 2656, 2700). D. DISCUTIBLE MARCADO: comparten el nucleo no culpar al trabajador, el "
 "sistema responde; quien pese ese nucleo dira A.")
add(2815, "D",
 "comite_cero_defectos (Grupo de Apoyo para el Programa Cero Defectos, Paso 7 de Crosby: elegir 3 "
 "o 4 personas de confianza, adaptar el concepto Cero Defectos al negocio, dejar claro que no es "
 "motivacion sino estandar, preparar el plan de implementacion) contra dia_cero_defectos (Dia de "
 "Cero Defectos: elegir una fecha unica de lanzamiento, actividades especiales que marquen el "
 "cambio, explicar el programa a todos el mismo dia). MISMA FUENTE Crosby, sim_tit 45,0. Son DOS "
 "pasos distintos del programa Cero Defectos de Crosby: formar el comite de apoyo (Paso 7) contra "
 "montar el evento del Dia Cero Defectos. Preparar el comite no es realizar el dia del "
 "lanzamiento. D. DISCUTIBLE MARCADO: ambos son piezas del mismo programa Cero Defectos; quien lea "
 "el programa como un solo acto dira A.")
add(2816, "A",
 "eliminacion_barreras_orgullo_del_trabajo (Eliminacion de Barreras al Orgullo del Trabajo, Punto "
 "12 de Deming: reunir los reportes repetidos de problemas sin resolver, revisar los sistemas de "
 "evaluacion y pago por pieza, plan para eliminar barreras con responsables y plazos, cambiar los "
 "discursos y carteles por acciones concretas) contra orgullo_por_el_trabajo (Orgullo por el "
 "Trabajo, Pride of Workmanship, Deming: hablar con las personas para identificar barreras "
 "concretas, crear una forma simple de reportar fallas con seguimiento, eliminar evaluaciones que "
 "generen miedo, que quien supervisa conozca el trabajo tecnico, actuar visible sobre las "
 "sugerencias). MISMA FUENTE Deming, sim_tit 50,5. Es el MISMO Punto 12: quitar las barreras al "
 "orgullo del trabajo. El acto entero coincide: identificar las barreras desde la gente y los "
 "reportes, quitar el miedo y las evaluaciones que lo generan, reemplazar los lemas por accion. "
 "Cada uno pone su ejemplo (pago por pieza en uno, canal de reporte en el otro) pero es el mismo "
 "acto, no dos caras. A por fusion mutua. DISCUTIBLE MARCADO fuerte: orgullo trae que el supervisor "
 "conozca el trabajo tecnico (roza el Punto 7) y eliminacion trae revisar el pago por pieza (roza "
 "el Punto 11); quien lea esos como pasos enteros propios dira D.")
add(2817, "D",
 "modelo_shingo_evaluacion_excelencia (Modelo Shingo de Evaluacion de Excelencia Operacional: "
 "definir las cuatro dimensiones cultura procesos alineacion resultados, aplicar la evaluacion "
 "diferenciando roles, valorar con escalas de madurez, identificar brechas actual contra deseado, "
 "ajustar pesos, repetir la autoevaluacion) contra shingo_enterprise_excellence_model (Modelo de "
 "Excelencia Empresarial de Shingo: diagnosticar la cultura actual, definir principios guia "
 "alineados a los valores, disenar o realinear sistemas de gestion, seleccionar herramientas que "
 "los soporten, medir resultados y retroalimentar hacia los principios). MISMA FUENTE Juran, con "
 "arista, sim_tit 71,6. Dos caras del Shingo: el primero es el INSTRUMENTO DE EVALUACION (escalas "
 "de madurez, brechas, pesos, autoevaluacion periodica); el segundo es el MODELO de construccion "
 "(principios, sistemas, herramientas, resultados). Evaluar la madurez no es disenar los sistemas "
 "desde los principios. D. DISCUTIBLE MARCADO fuerte: ambos son el modelo Shingo con sim_tit alta "
 "y arista; quien los lea como el mismo marco descrito dos veces dira A.")
add(2818, "D",
 "accion_correctiva_2 (De la Deteccion a la Prevencion, Crosby: observar rechazos reales, analisis "
 "de tendencias para lo menos obvio, causa raiz sistemica no culpar, cambios que prevengan la "
 "recurrencia) contra prevencion_gestion_calidad (Prevencion como Filosofia Central, Crosby: "
 "destinar tiempo y presupuesto a prevencion como pruebas y capacitacion, controles en cada etapa "
 "antes de las fallas, mantenerte cerca de los resultados, tener claro costo y beneficio antes de "
 "invertir en prevencion). MISMA FUENTE Crosby, sim_tit 50,9. Actos distintos: el 2 es ACCION "
 "CORRECTIVA que gira hacia prevenir (parte de rechazos y tendencias reales para evitar la "
 "recurrencia); prevencion_gestion es la FILOSOFIA PREVENTIVA proactiva (invertir antes de que "
 "haya fallas, controles por etapa). Reaccionar a lo detectado para prevenir no es invertir "
 "adelante en prevencion. Ambos quedaron D contra prevencion_versus_control_de_calidad (2689, "
 "2604). D. DISCUTIBLE MARCADO: comparten la palabra prevencion como meta; quien pese eso dira A.")
add(2819, "D",
 "definicion_sistema_calidad_proveedor (Definicion del Sistema de Calidad del Proveedor: ver si se "
 "requieren controles de proceso como SPC o sanitarios, referenciar normas ISO 9000 o TS 16949 en "
 "el contrato, pedir plan de confiabilidad o FMECA si el producto es complejo, verificar expertise "
 "real) contra especificacion_requisitos_proveedores (Especificacion de Requisitos de Calidad "
 "para Proveedores: comunicar el uso final y las condiciones de operacion, obtener evidencia de la "
 "capacidad del proveedor, redactar las especificaciones de producto y de sistema de calidad del "
 "proveedor, considerar contratos de desarrollo si es complejo). MISMA FUENTE Juran, con arista, "
 "sim_tit 69,9. FICHA CONTRA MAPA: especificacion es el requisito AMPLIO (uso, capacidad, "
 "especificacion de producto Y de sistema de calidad, contratos de desarrollo) y solo NOMBRA la "
 "especificacion del sistema de calidad como uno de sus pasos; definicion_sistema DESPLIEGA ese "
 "paso (SPC, normas, FMECA, expertise). Cada uno trae ademas pasos enteros propios (uso final y "
 "capacidad en uno, FMECA y expertise en el otro). D. DISCUTIBLE MARCADO fuerte: con arista y "
 "sim_tit 69,9, quien lea la definicion del sistema como contenida en el paso 3 de la "
 "especificacion dira A.")
add(2820, "D",
 "enfoque_en_procesos_no_en_problemas (Enfocarse en los Procesos no Solo en los Problemas, Deming: "
 "documentar los problemas recurrentes, identificar el proceso comun que genera cada categoria, "
 "aplicar PDCA al proceso raiz no al sintoma, verificar que la solucion elimina la recurrencia) "
 "contra mejora_continua_del_proceso (Mejora Continua del Proceso, Never Ending Improvement, "
 "Deming: preguntar a diario que se hizo para mejorar el conocimiento, evaluar si cada producto es "
 "mejor, trabajar en procesos y materiales no solo en resultados, verificar el control estadistico "
 "del producto final, reducir a un proveedor unico por colaboracion). MISMA FUENTE Deming, sim_tit "
 "40,0. El primero es un metodo de SOLUCION dirigido al proceso detras de los problemas "
 "recurrentes (documentar, hallar el proceso comun, PDCA la raiz); el segundo es la FILOSOFIA de "
 "mejora continua sin fin (aprendizaje diario, proveedor unico, control estadistico). Atacar el "
 "proceso raiz de un problema no es la mejora perpetua del negocio. D. DISCUTIBLE MARCADO: ambos "
 "trabajan sobre el proceso y no el sintoma; quien pese ese nucleo dira A.")
add(2821, "D",
 "benchmarking_7_pasos_juran (Proceso de Benchmarking de 7 Pasos de Juran: definir areas y KPIs, "
 "recolectar y validar datos, normalizar con factores de complejidad, informe con brechas, "
 "talleres de transferencia de mejores practicas, plan de accion e implementarlo, institucionalizar "
 "con capacitacion) contra monitoreo_continuo_benchmarking (Benchmarking Continuo: establecer un "
 "ciclo periodico anual, comparar ano contra ano para medir tendencias propias, validar el metodo "
 "de normalizacion, ajustar el plan segun la evolucion del grupo). MISMA FUENTE Juran, sim_tit "
 "47,6. El primero es el PROCESO completo de un ciclo de benchmarking (siete pasos, de preparar a "
 "institucionalizar); el segundo es el SOSTENIMIENTO periodico (ciclo anual, tendencia ano contra "
 "ano). Correr el proceso de siete pasos no es el monitoreo perpetuo. Coincide con la familia del "
 "benchmarking que separa cada nodo en cara distinta (reporte 2800). D. DISCUTIBLE MARCADO: el "
 "paso 7 institucionaliza y el continuo tambien sostiene; quien pese ese solape dira A.")
add(2822, "D",
 "control_estadistico_de_procesos_2 (SPC mediante Graficos de Control, Deming: recolectar datos en "
 "muestras n igual 4 o 5, calcular promedio y rango, establecer limites 3 sigma del rango "
 "promedio, graficar en el tiempo, investigar los puntos fuera como causa especial) contra "
 "graficos_de_control_uso (Dos Usos Basicos de los Graficos de Control, Deming: definir si el "
 "grafico evalua un lote pasado o sirve de monitoreo continuo, extender los limites hacia "
 "adelante, capacitar al operario para ignorar la fluctuacion normal, revisar la vigencia del "
 "grafico). MISMA FUENTE Deming, sim_tit 60,2. METODO CONTRA ENCUADRE: el primero CONSTRUYE y "
 "corre el grafico (muestras, limites, puntos fuera); el segundo distingue los DOS USOS del "
 "grafico (analizar un lote pasado contra monitorear hacia adelante). Construir el grafico no es "
 "la distincion de para que se usa. D. DISCUTIBLE MARCADO: ambos son el grafico de control con "
 "limites 3 sigma; quien pese ese nucleo dira A.")
add(2823, "D",
 "dmaic_fase_analyze (DMAIC Fase Analyze: analisis grafico exploratorio con histogramas box plots "
 "y Pareto, correlacion y regresion, pruebas de hipotesis t ANOVA chi cuadrado, confirmar los "
 "pocos vitales Xs) contra dmaic_fase_improve (DMAIC Fase Improve: planificar los experimentos DOE, "
 "experimentos de screening, factoriales 2k para modelar, RSM o EVOP, evaluar alternativas, "
 "disenar e implementar la mejora). MISMA FUENTE Juran, con arista, sim_tit 41,5. FASE CONTRA "
 "FASE: son dos fases distintas del DMAIC, Analyze (hallar y confirmar las causas vitales) contra "
 "Improve (experimentar y disenar la mejora). Como las fases de un roadmap salen D entre si (la "
 "vara del 2798), Analyze no es Improve. D. DISCUTIBLE MARCADO: ambas son fases del mismo DMAIC "
 "con analisis de datos; quien lea el DMAIC como un solo acto dira A.")
add(2824, "D",
 "diseno_de_metodos_de_recoleccion_de_datos (Diseno y Prueba de Metodos de Recoleccion de Datos, "
 "Juran: identificar las fuentes y quien da los datos, disenar formularios que minimicen esfuerzo "
 "y errores, determinar la informacion adicional para rastrear, hacer un MSA para confirmar la "
 "precision, revisar el proceso y validar los resultados) contra "
 "recoleccion_validacion_datos_benchmarking (Como Recolectar y Validar los Datos para tu "
 "Comparacion de Benchmarking: documento con validaciones automaticas, canal de ayuda durante el "
 "proyecto, revisiones automaticas de datos raros, revisar completitud, integridad y consistencia "
 "contra el historico, sesion de resolucion o data clinic). MISMA FUENTE Juran, sim_tit 36,7. El "
 "primero es el metodo GENERAL de diseno de la recoleccion con su MSA para la precision; el segundo "
 "es la recoleccion y validacion PROPIA de un benchmarking (validaciones automaticas, triple "
 "chequeo completitud integridad consistencia, data clinic). Cada uno trae pasos enteros propios "
 "(MSA en uno, el triple chequeo y el data clinic en el otro). D. DISCUTIBLE MARCADO: ambos disenan "
 "un formulario que minimiza errores; quien pese ese nucleo dira A.")
add(2825, "A",
 "cinco_suposiciones_erroneas_calidad (Las Cinco Suposiciones Erroneas sobre la Calidad, Crosby: "
 "revisar cuales estan presentes, aprender la definicion correcta y medirla por costos, buscar el "
 "origen real de los defectos, redefinir el rol de quien revisa la calidad) contra "
 "concepto_supuestos_erroneos_sobre_calidad (Supuestos Erroneos Convencionales sobre la Calidad, "
 "Crosby: entrevistar a los gerentes para identificar sus supuestos, confrontar cada supuesto con "
 "su contraparte correcta calidad igual conformidad, es medible, el error no es inevitable, la "
 "gente si puede, disenar sesiones de sensibilizacion, usar testimonios de gerentes que "
 "cambiaron). MISMA FUENTE Crosby, sim_tit 73,5. Es el MISMO concepto de Crosby, los supuestos "
 "erroneos convencionales sobre la calidad: identificar los supuestos presentes y confrontarlos "
 "con su contraparte correcta es el acto entero compartido (revisar cuales estan presentes igual "
 "entrevistar para identificarlos; aprender la definicion correcta igual confrontar con la "
 "contraparte). A por fusion mutua, superviviente POR ELEGIR. DISCUTIBLE MARCADO fuerte: concepto "
 "trae las sesiones y los testimonios como despliegue y cinco trae buscar el origen real de los "
 "defectos; quien lea esos como pasos enteros propios que rompen la contencion dira D, distinto de "
 "su vecino Deming del 2806 que si es D.")

out = io.open("docs/loop/_lote.jsonl", "w", encoding="utf-8", newline="\n")
for x in lote:
    out.write(json.dumps(x, ensure_ascii=False) + "\n")
out.close()
print("escritos %d veredictos, puestos %d..%d" % (len(lote), lote[0]["puesto"], lote[-1]["puesto"]))
import collections
print("clases:", dict(collections.Counter(x["clase"] for x in lote)))
