# -*- coding: utf-8 -*-
# constructor del lote del tramo 2826-2850. escribe docs/loop/_lote.jsonl.
import json, io, collections
lote = []
def add(p, c, r):
    assert "—" not in r and "–" not in r, "guion largo en %d" % p
    lote.append({"puesto": p, "clase": c, "razon": r})

add(2826, "D",
 "estadistica_basica_calidad (Estadistica Basica para Analisis de Calidad: determinar el tipo de "
 "dato, calcular tendencia central media mediana moda, calcular dispersion rango varianza "
 "desviacion, definir el esquema de muestreo y el tamano, verificar que la muestra sea sin sesgo y "
 "representativa) contra medidas_tendencia_dispersion (Medidas de Tendencia Central y Dispersion: "
 "media aritmetica, mediana si hay asimetria, desviacion o rango segun la muestra, coeficiente de "
 "variacion al comparar grupos, no eliminar extremos sin causa especial). MISMA FUENTE Juran, "
 "sim_tit 42,9. FICHA CONTRA MAPA: la basica es el panorama que ademas DISENA el muestreo y valida "
 "la muestra (pasos enteros propios de adquisicion del dato); las medidas son solo el bloque de "
 "calculo (tendencia y dispersion) con el detalle del CV y los extremos. Disenar el muestreo no es "
 "calcular la media. D. DISCUTIBLE MARCADO fuerte: las medidas caben casi enteras en los pasos 2 y "
 "3 de la basica; quien lea eso como contencion dira A.")
add(2827, "D",
 "capacidad_proceso_concepto (Capacidad de Proceso: confirmar el control estadistico, definir "
 "maquina metodo material personas, recolectar datos estables, calcular la sigma del proceso, "
 "comparar 6 sigma contra los limites de especificacion, usar para decisiones) contra indice_cpk "
 "(Indice Cpk: calcular media y sigma, distancia de la media a USL y LSL, Cpk como el minimo, "
 "comparar Cpk con Cp para ver descentrado, actuar si Cpk menor a Cp). MISMA FUENTE Juran, con "
 "arista, sim_tit 53,3. El concepto es el ESTUDIO de capacidad entero (control, definir, medir "
 "sigma, comparar contra especificacion); el Cpk es UN indice centrado derivado. Extiende la "
 "familia de la capacidad que sigue SIN ACTO y toda D (2454, 2569, 2591 contra el concepto; el "
 "nucleo 10 de 10 del reporte 2800). D. DISCUTIBLE MARCADO: el Cpk sale del estudio de capacidad; "
 "quien lo lea como contenido en el concepto dira A.")
add(2828, "D",
 "dia_cero_defectos (Dia de Cero Defectos: elegir una fecha unica de lanzamiento, actividades "
 "especiales que marquen el cambio, explicar el programa a todos el mismo dia) contra "
 "fijacion_de_metas (Fijar metas de mejora, Paso 10 de Crosby: una semana despues del Dia ZD cada "
 "grupo propone dos metas medibles, retadoras, publicarlas, reconocer a quien mejora, usar medidas "
 "de corto plazo). MISMA FUENTE Crosby, con arista, sim_tit 36,4. Son DOS pasos distintos del "
 "programa Cero Defectos: el evento del Dia ZD (Paso 9) contra la fijacion de metas (Paso 10). La "
 "arista es la secuencia (las metas se fijan una semana despues del Dia), no la identidad. Cada uno "
 "tiene su gemelo real: dia =A= dia_cero_defectos_2 (2491), fijacion =A= establecimiento_metas "
 "(2699). Realizar el dia de lanzamiento no es fijar las metas. D. DISCUTIBLE MARCADO: ambos son "
 "pasos consecutivos del mismo programa; quien lea el programa como un solo acto dira A.")
add(2829, "D",
 "accion_correctiva_6 (Destapar Causas, Rolling Over the Rocks, Crosby: documentar via auditorias, "
 "investigar la causa raiz, asignar responsables y plazos, verificar que se elimino) contra "
 "mejora_continua_operaciones (Enfoque de Mejora Continua en Operaciones, Juran: diagnosticar la "
 "cultura de calidad, clasificar cada problema esporadico o cronico, resolver de inmediato el "
 "esporadico, atacar el cronico de raiz, sumar otras areas, pedir soporte tecnico y capacitacion). "
 "FUENTES DISTINTAS, sim_tit 37,6. Uno es la ACCION CORRECTIVA de Crosby (destapar y cerrar los "
 "problemas detectados); el otro es el ENFOQUE DE MEJORA de Juran (cultura, esporadico contra "
 "cronico). La familia lo confirma: accion_correctiva_5 =D= mejora_continua_operaciones (2692) y 6 "
 "vive en el cumulo de 5. D. DISCUTIBLE MARCADO: ambos atacan la causa raiz; quien pese ese nucleo "
 "dira A.")
add(2830, "D",
 "cuestionario_autoevaluacion_gerencial_calidad (Cuestionario de Autoevaluacion para la "
 "Transformacion de Calidad, Deming: responder cada bloque con honestidad, anotar donde hay "
 "obstaculos como constancia de proposito o gestion por numeros, priorizar las brechas mayores, "
 "repetir el cuestionario para medir el avance) contra los_14_puntos_deming (Los 14 Puntos de "
 "Deming: revisar cada punto y como aplica, diagnosticar cuanto te alejas de cada uno, disenar un "
 "plan de transformacion integrado, dejar claro que es responsabilidad de todos). MISMA FUENTE "
 "Deming, con arista, sim_tit 64,5. INSTRUMENTO CONTRA MARCO: el cuestionario es la herramienta de "
 "autoevaluacion periodica (responder, anotar obstaculos, priorizar, repetir); los 14 puntos son el "
 "marco y el plan de transformacion. Evaluarte con el cuestionario no es el plan de los 14 puntos, "
 "igual que el modelo Shingo separa evaluacion de modelo (2817). D. DISCUTIBLE MARCADO fuerte: el "
 "cuestionario mide justo los 14 puntos y las enfermedades; quien lo lea como el mismo diagnostico "
 "dira A.")
add(2831, "D",
 "niveles_calidad_muestreo_aql_lql_aoql (Indices de Calidad para Planes de Muestreo AQL LQL IQL "
 "AOQL: definir el AQL aceptable, fijar el LQL o LTPD y el riesgo del consumidor, calcular el AOQL "
 "como peor caso de salida, comunicar que el AQL no autoriza enviar no conforme) contra "
 "seleccion_plan_muestreo_ansi_z14 (Seleccion y Aplicacion de Planes ANSI ASQC Z1.4: determinar "
 "AQL tamano de lote y nivel, consultar la tabla de letras de codigo, leer el plan en la tabla "
 "maestra, aplicar reglas de cambio a inspeccion estricta o reducida). MISMA FUENTE Juran, con "
 "arista, sim_tit 50,4. CONCEPTO CONTRA PROCEDIMIENTO: el primero DEFINE los indices de calidad "
 "del muestreo y su significado y advertencia; el segundo APLICA la norma Z1.4 con sus tablas de "
 "letras de codigo y reglas de conmutacion. Definir el AQL no es leer el plan en la tabla maestra. "
 "niveles ya salio D contra su hermano (2795). D. DISCUTIBLE MARCADO: la seleccion usa el AQL que "
 "el otro define; quien lea eso como contencion dira A.")
add(2832, "D",
 "eliminacion_barreras_orgullo_del_trabajo (Eliminacion de Barreras al Orgullo del Trabajo, Punto "
 "12 de Deming: reunir los reportes repetidos, revisar la evaluacion y el pago por pieza, plan con "
 "responsables y plazos, cambiar los lemas por accion) contra remover_barreras_orgullo_trabajo "
 "(Remover Barreras al Orgullo por el Trabajo Bien Hecho: conversar para identificar barreras "
 "especificas, clasificarlas por origen material equipo supervision comunicacion, priorizar y "
 "asignar responsable, crear un canal de retroalimentacion continua). MISMA FUENTE Deming, sim_tit "
 "68,7. D POR TRANSITIVIDAD DE DOS SUBCUMULOS: eliminacion =A= orgullo_por_el_trabajo (2816) pero "
 "remover =D= orgullo_por_el_trabajo (2450), y remover vive con barreras_orgullo_trabajo (2516 A) "
 "que a su vez =D= orgullo (2564). Eliminacion cae en el cumulo del orgullo y remover en el de "
 "barreras, y esos dos cumulos estan separados. El contenido lo respalda: remover trae clasificar "
 "las barreras por origen como paso entero propio, eliminacion trae revisar el pago por pieza y "
 "cambiar los lemas. D. DISCUTIBLE MARCADO fuerte: sim_tit 68,7 y ambos literalmente barreras al "
 "orgullo del trabajo, la lectura ingenua dira A; la separacion de los dos subcumulos via el "
 "orgullo la vuelve D.")
add(2833, "D",
 "carta_de_control_shewhart (Carta de Control de Shewhart, Juran: recolectar datos en el tiempo, "
 "calcular la linea central y los limites, graficar y clasificar dentro o fuera, si dentro asumir "
 "causas comunes, si fuera investigar causa especial, justificar el uso segun impacto en cliente "
 "seguridad o economia) contra control_estadistico_de_procesos_2 (SPC mediante Graficos de "
 "Control, Deming: recolectar muestras n 4 o 5, promedio y rango, limites 3 sigma del rango "
 "promedio, graficar en el tiempo, investigar los puntos fuera). FUENTES DISTINTAS, sim_tit 43,2. "
 "El cumulo de las cartas de control separa cada variante con fuerza: control_estadistico_2 =A= "
 "control_estadistico_de_procesos (2590, su gemelo) y =D= todos los demas (2518, 2567, 2706, 2822); "
 "carta_shewhart =D= control_charts_shewhart (2558, su hermano). Ademas carta trae justificar el "
 "uso por impacto como paso propio (el encuadre) y control_estadistico_2 la mecanica de muestras y "
 "rango. D. DISCUTIBLE MARCADO fuerte: ambos construyen e interpretan una carta Shewhart con "
 "causas comunes contra especiales; quien pese ese nucleo dira A.")
add(2834, "D",
 "costo_de_calidad_diagnostico (Evolucion del Costo de Calidad como Indicador de Madurez, Crosby: "
 "calcular el costo de calidad con todos los rubros, comparar el calculo inicial contra uno "
 "exhaustivo, usar la cifra como argumento para invertir en prevencion, seguir la tendencia como "
 "medida de madurez) contra impacto_calidad_ingresos_costos (Impacto de la Calidad en Ingresos y "
 "Costos, Juran: analizar la percepcion del cliente sobre lo que te diferencia, comparar ventas "
 "contra competidores de menor calidad, ver la relacion calidad y recompra, evaluar precio "
 "premium, monitorear ingresos, incluir metricas de ingreso no solo de costo). FUENTES DISTINTAS, "
 "sim_tit 57,1. Caras opuestas: el primero mide el COSTO de la calidad (rubros internos, madurez); "
 "el segundo mide el INGRESO (percepcion, recompra, premium) y hasta advierte no quedarse solo en "
 "el costo. El cumulo del costo de calidad es todo D (2459, 2580, 2626, 2698, 2721); impacto salio "
 "D contra COPQ (2729). D. DISCUTIBLE MARCADO: ambos ligan calidad con dinero para priorizar; "
 "quien pese ese marco dira A.")
add(2835, "D",
 "abolir_inspeccion_masiva (Abolicion de la Inspeccion Masiva, Punto 3 de Deming: medir el costo "
 "de la inspeccion al 100 por ciento y su retrabajo, analizar la causa raiz de los defectos, "
 "implementar muestreo aleatorio, redisenar el proceso para construir calidad desde el origen, "
 "reducir gradualmente la inspeccion masiva) contra reporte_gerencial_diagnostico_calidad "
 "(Diagnostico de fallas en el sistema de calidad, Deming: revisar los datos historicos de "
 "auditoria, documentar como funciona la deteccion realmente, revisar el pago por pieza, escribir "
 "un diagnostico con causas raiz y opciones, eliminar la distincion arbitraria mayor menor). MISMA "
 "FUENTE Deming, con arista, sim_tit 39,6. Actos distintos: el primero es la ESTRATEGIA de abolir "
 "la inspeccion masiva (construir calidad desde el origen); el segundo es ESCRIBIR un diagnostico "
 "del sistema de calidad (auditoria historica, opciones, definiciones de defecto). abolir es todo "
 "D en su familia (2560, 2767, 2788). D. DISCUTIBLE MARCADO: ambos analizan la causa raiz de los "
 "defectos; quien pese ese paso comun dira A.")
add(2836, "D",
 "bucle_retroalimentacion_control (El Bucle de Retroalimentacion, Feedback Loop, Juran: instalar "
 "un sensor, definir la unidad de medida y el estandar, poner un arbitro que compare real contra "
 "meta, disenar un actuador que corrija, registrar cada ciclo) contra control_calidad_definicion "
 "(Control de Calidad como Proceso Universal, Trilogia de Juran: identificar la zona de control "
 "estable deficiente o mejorado, diferenciar control de mejora, poner nuevos controles tras cada "
 "mejora, aplicar control a proceso y producto). MISMA FUENTE Juran, con arista, sim_tit 53,1. "
 "MECANISMO CONTRA CONCEPTO: el primero es el mecanismo concreto del lazo (sensor, arbitro, "
 "actuador, registro); el segundo es el CONCEPTO de control dentro de la trilogia (zonas, control "
 "contra mejora). control_calidad_definicion ya salio D contra la trilogia (2769). Armar el lazo "
 "no es la definicion de control de la trilogia. D. DISCUTIBLE MARCADO: ambos son control de "
 "calidad comparando contra un estandar; quien pese ese eje dira A.")
add(2837, "D",
 "accion_correctiva_4 (Accion Correctiva, Paso 6, Crosby: reuniones regulares de supervision para "
 "los problemas de calidad, escalar lo no resuelto al siguiente nivel, crear reuniones formales "
 "donde no las haya, seguimiento visible) contra eliminacion_causas_error (Eliminacion de Causas "
 "de Error, Paso 11 de Crosby: formulario simple de una pagina para reportar obstaculos al trabajo "
 "sin errores, grupos funcionales que resuelven cada tipo, acuse dentro de 24 horas, seguimiento y "
 "comunicar las soluciones). MISMA FUENTE Crosby, sim_tit 48,5. Son DOS pasos distintos del "
 "programa Crosby: la accion correctiva por estructura de reuniones (Paso 6) contra la eliminacion "
 "de causas de error o ECR, el formulario donde el trabajador reporta obstaculos (Paso 11). Cada "
 "uno con su gemelo aparte (eliminacion_causas_error =D= _2 en 2416; accion_correctiva_4 =D= "
 "crosby y 5). D. DISCUTIBLE MARCADO: ambos reportan, asignan y dan seguimiento; quien pese ese "
 "patron dira A.")
add(2838, "A",
 "analisis_causa_raiz_diagnostico (Analisis de Causa Raiz mediante Diagnostico Sistematico, Juran: "
 "Pareto para descartar variables, generar teorias, disenar la recoleccion para correlacionar cada "
 "teoria, validar estadisticamente cual explica la mayoria, confirmar la causa raiz ANTES de "
 "disenar el remedio) contra viaje_diagnostico_remedial (Viaje Diagnostico y Viaje Remedial, "
 "Juran: analizar sintomas, formular teorias, probar con datos, establecer la causa raiz, disenar "
 "remedios, probarlos en condiciones reales, gestionar la resistencia, poner nuevos controles). "
 "MISMA FUENTE Juran, sim_tit 49,4. A POR CONTENCION: analisis_causa_raiz es el VIAJE DIAGNOSTICO "
 "entero y se detiene explicitamente antes del remedio; viaje_diagnostico_remedial es ese mismo "
 "viaje diagnostico (sintomas, teorias, probar, causa raiz) MAS el viaje remedial completo "
 "(remedios, prueba, resistencia, controles) como pasos del superviviente. El diagnostico cabe "
 "entero en el diagnostico mas remedial, y analisis no trae ningun paso propio que viaje no tenga. "
 "Es la contencion del 2618 y del 2645, no la ficha de una fase del 2678. analisis_causa_raiz ya "
 "tiene su gemelo diagnostico (2600 A). A, superviviente viaje_diagnostico_remedial. DISCUTIBLE "
 "MARCADO fuerte: quien lea el viaje diagnostico como una PARTE contra el mapa de los dos viajes, "
 "o como cara distinta por su Pareto y validacion estadistica, dira D.")
add(2839, "D",
 "benchmarking_mejores_practicas (Benchmarking de Mejores Practicas, Juran: identificar los "
 "procesos clave a comparar, seleccionar organizaciones mejores en su clase, hacer o subcontratar "
 "el estudio, identificar las brechas) contra monitoreo_continuo_benchmarking (Benchmarking "
 "Continuo: ciclo periodico anual, comparar ano contra ano, validar la normalizacion, ajustar el "
 "plan segun la evolucion del grupo). MISMA FUENTE Juran, sim_tit 59,3. D POR TRANSITIVIDAD: "
 "benchmarking_mejores_practicas =A= benchmarking_proceso (2545) mientras monitoreo_continuo =D= "
 "benchmarking_proceso (2649), asi que caen a lados distintos. Uno es el ESTUDIO puntual de "
 "mejores practicas (seleccionar los mejores en clase, brechas); el otro es el SOSTENIMIENTO "
 "periodico (ciclo anual, tendencia). Igual que 2821. D. DISCUTIBLE MARCADO: ambos comparan contra "
 "los mejores; quien pese ese eje dira A.")
add(2840, "D",
 "aprobacion_alta_direccion (Tu Compromiso Personal con el Cambio, Juran: reunir evidencia de "
 "amenazas competitivas, cuantificar oportunidades con el costo de la mala calidad, definir que no "
 "puedes delegar, revisiones periodicas de tu avance, reconocer que sumara un 10 por ciento mas de "
 "trabajo) contra inhibidores_del_breakthrough (Barreras que frenan un avance real, Juran: "
 "identificar cuales barreras estan presentes, aclarar gastar mas por sumar contra gastar menos "
 "por reducir desperdicio, abrir un canal para las dudas de quien te ayuda, no delegar todo, "
 "explicar el por que antes de los rumores). MISMA FUENTE Juran, con arista, sim_tit 37,1. Actos "
 "distintos: el primero es el COMPROMISO PERSONAL del lider (tareas no delegables, 10 por ciento "
 "mas de trabajo, autorevision); el segundo es identificar y quitar las BARRERAS al breakthrough. "
 "aprobacion =D= practicas_gerenciales_no_delegables (2738), inhibidores =D= gestion_resistencia "
 "(2511). D. DISCUTIBLE MARCADO: comparten no delegar y la involucracion del lider; quien pese ese "
 "nucleo dira A.")
add(2841, "D",
 "auditoria_de_producto (Revision independiente de producto terminado, Juran: comparar contra "
 "especificaciones o necesidades del usuario, elegir el momento fabrica distribuidor o campo, "
 "cuantas unidades, que mirar, comparar con quejas y mercado, clasificar fallas por gravedad con "
 "indice por unidad, comparar en el tiempo y contra la competencia) contra auditoria_negocio "
 "(Auditoria de Negocio, Business Audit, Juran: identificar las preguntas clave, recopilar y "
 "analizar la informacion, comparar contra criterios externos o propios, revisar hallazgos con "
 "calma, definir acciones). MISMA FUENTE Juran, sim_tit 37,0. Alcances distintos: la de producto "
 "revisa el PRODUCTO terminado (indice de fallas por unidad, contra la competencia); la de negocio "
 "es una auditoria GENERAL del negocio (preguntas, criterios, acciones). auditoria_de_producto es "
 "todo D en su familia (2433, 2478); auditoria_negocio =D= sus hermanas (2635, 2749). D. "
 "DISCUTIBLE MARCADO: ambas son auditorias que comparan contra un criterio; quien pese eso dira A.")
add(2842, "D",
 "planes_de_muestreo_de_aceptacion (Planes de Muestreo de Aceptacion, Juran: definir el promedio "
 "de proceso del proveedor, calcular el costo del dano por defectos no detectados, balancear 100 "
 "por ciento contra muestreo, disenar la curva OC, considerar errores de medicion) contra "
 "tipos_planes_muestreo_atributos_variables (Planes por Atributos y por Variables: ver si las "
 "caracteristicas son medibles o pasa no pasa, elegir variables o atributos, calcular tamano y "
 "criterios segun la norma). MISMA FUENTE Juran, sim_tit 60,0. Ejes distintos: el primero es el "
 "DISENO economico del plan (costo del dano, curva OC, errores de medicion); el segundo es la "
 "eleccion del TIPO por dato (atributos contra variables). Es la misma relacion que 2810 "
 "(estructura de muestras contra tipo de dato, D). planes =D= sus hermanos del muestreo (2702, "
 "2753); tipos =D= single_double_multiple (2810). D. DISCUTIBLE MARCADO: ambos eligen un plan de "
 "muestreo; quien pese ese marco comun dira A.")
add(2843, "D",
 "value_non_value_added_analysis (Analisis de Valor Agregado y No Agregado VA NVA, Juran: listar "
 "cada paso desde el mapa de estado actual, preguntar si el cliente pagaria por el, clasificar "
 "valor agregado o no necesario o desperdicio puro, disenar acciones para reducir el desperdicio) "
 "contra value_stream_mapping (Value Stream Mapping, Metricas del Proceso, Juran: documentar el "
 "flujo actual de materiales e informacion, registrar tiempo de ciclo y costo por etapa, "
 "identificar puntos de desperdicio, priorizar como proyectos de mejora). MISMA FUENTE Juran, con "
 "arista, sim_tit 34,5. D POR TRANSITIVIDAD Y FICHA CONTRA MAPA: value_stream_mapping =A= "
 "mapeo_flujo_valor (2500) mientras VA NVA =D= mapeo_flujo_valor (2735), asi que caen a lados "
 "distintos. El VA NVA es la ficha del paso de CLASIFICAR el valor de cada paso, que toma como "
 "insumo el mapa; el VSM es el mapa del flujo con sus metricas. Ficha contra mapa, como ya se "
 "dictamino en 2735. D. DISCUTIBLE MARCADO: el VA NVA vive dentro del VSM; quien lo lea como "
 "contenido a favor de fusion dira A.")
add(2844, "D",
 "herramientas_analisis_causa_raiz (Herramientas Graficas de Analisis de Datos, graficos "
 "histogramas box plots Pareto dispersion estratificacion: recolectar datos, seleccionar la "
 "herramienta segun el analisis, construir y analizar, Pareto para priorizar, estratificar) contra "
 "histogramas_distribucion_frecuencias (Histogramas y Distribucion de Frecuencias: recopilar al "
 "menos 40 puntos u 8 para box plot, organizar en intervalos, graficar la frecuencia, analizar la "
 "forma, comparar con box plots). MISMA FUENTE Juran, sim_tit 42,6. FICHA CONTRA MAPA: "
 "herramientas es el MENU de tecnicas graficas (histograma, box plot, Pareto, dispersion, "
 "estratificacion) y solo nombra el histograma como una; histogramas ES el histograma desplegado. "
 "Ya esta dictado: herramientas =D= histograma (2720), =D= box plot (2647), =D= graficos (2757); "
 "histogramas tiene su gemelo en histograma (2517 A). El menu tiene Pareto y estratificacion que "
 "el histograma no trae. D. DISCUTIBLE MARCADO: el histograma esta en el menu; quien lea eso como "
 "contencion dira A.")
add(2845, "D",
 "rol_de_mandos_medios_y_supervisores (Liderar la calidad sin ser quien manda, Juran: desarrollar "
 "liderazgo para coordinar equipos que no te responden, definir quien detecta y nombra los "
 "problemas, fomentar la participacion en grupos de trabajo, evaluar habilidades como la "
 "tolerancia a fallas y la flexibilidad) contra rol_director_calidad (Quien se encarga de la "
 "calidad, Juran: separar las tareas de calidad del dia a dia de las nuevas estrategicas, pasar "
 "actividades a quienes ejecutan, capacitarlos, actuar como asesor estrategico, supervisar que la "
 "estrategia se cumpla). MISMA FUENTE Juran, sim_tit 48,8. Roles distintos: el mando medio o "
 "supervisor que lidera sin autoridad formal y coordina equipos ajenos, contra el director de "
 "calidad que delega a la linea y asesora en la estrategia. El cumulo de los roles de calidad "
 "separa cada nodo: rol_director_calidad es todo D (2472, 2654, 2764, 2783, 2796). D. DISCUTIBLE "
 "MARCADO: ambos coordinan calidad con quienes no dependen directo; quien pese ese solape dira A.")
add(2846, "D",
 "accion_correctiva_4 (Accion Correctiva, Paso 6, Crosby: reuniones regulares de supervision, "
 "escalar lo no resuelto, crear reuniones formales, seguimiento visible) contra accion_correctiva_6 "
 "(Destapar Causas, Rolling Over the Rocks, Crosby: documentar via auditorias, investigar la causa "
 "raiz, asignar responsables y plazos, verificar). MISMA FUENTE Crosby, sim_tit 46,5. D POR "
 "TRANSITIVIDAD DEL CUMULO: accion_correctiva_4 =D= accion_correctiva_crosby (2553) pero "
 "accion_correctiva_6 =A= accion_correctiva_crosby (2426), asi que 4 y 6 caen a lados distintos. "
 "El 4 es la ESTRUCTURA de reuniones y escalamiento; el 6 es el lazo de auditoria, causa raiz y "
 "verificacion. El 4 quedo fuera del cumulo A de la accion correctiva (D contra crosby y contra 5 "
 "en 2747). D. DISCUTIBLE MARCADO: ambos son la accion correctiva Paso 6 con seguimiento; quien "
 "pese ese titulo comun dira A.")
add(2847, "D",
 "autocontrol_planificacion_servicio (Planifica el autocontrol en tu servicio, Self Control, "
 "Juran: documentar procedimientos claros, definir estandares de calidad y cantidad, revisar con "
 "retroalimentacion oportuna, disenar el proceso para que puedas cumplir, ajustar y hacer "
 "mantenimiento preventivo) contra diseno_servicio_calidad (Disena la calidad de tu servicio desde "
 "el inicio, Juran: arrancar el proyecto de diseno, identificar clientes, descubrir sus "
 "necesidades, definir las caracteristicas, disenar el proceso de servicio, poner controles y "
 "ponerlo a funcionar). MISMA FUENTE Juran, sim_tit 45,1. Actos distintos: el primero es el "
 "AUTOCONTROL (las condiciones para que quien trabaja regule su propia tarea: saber que hacer, "
 "como va, poder ajustar); el segundo es el DISENO del servicio desde cero (clientes, necesidades, "
 "caracteristicas, proceso, controles), el cascadeo QbD para servicio. Disenar el servicio no es "
 "el autocontrol de quien lo opera. D. DISCUTIBLE MARCADO: ambos terminan poniendo controles al "
 "proceso; quien pese ese paso final compartido dira A.")
add(2848, "D",
 "accion_correctiva (Accion Correctiva, Esporadica contra Cronica, Juran: clasificar la no "
 "conformidad esporadica o cronica, para la esporadica hacer una autopsia forense y comparar datos "
 "antes y despues, reconstruir la cronologia de eventos, restaurar el proceso al estado previo, "
 "para la cronica organizar un proyecto formal de mejora) contra mejora_continua_operaciones "
 "(Enfoque de Mejora Continua en Operaciones, Juran: diagnosticar la cultura, clasificar esporadico "
 "o cronico, resolver el esporadico de inmediato, atacar el cronico de raiz, sumar otras areas, "
 "pedir soporte y capacitacion). MISMA FUENTE Juran, sim_tit 31,7. Comparten la clasificacion "
 "esporadico contra cronico, pero cada uno trae su acto entero propio: accion_correctiva la "
 "autopsia forense y restaurar al estado previo (corregir); mejora_continua diagnosticar la "
 "cultura y sumar otras areas (mejorar). Restaurar al estado previo no es la mejora continua de la "
 "operacion, y accion_correctiva ya salio D contra 6 y 5 (2717, 2731), mejora_continua D contra 5 "
 "(2692). D. DISCUTIBLE MARCADO: comparten la clasificacion esporadico contra cronico entera; "
 "quien pese ese nucleo dira A.")
add(2849, "D",
 "concepto_de_auditoria_de_calidad (Concepto y Tipos de Auditoria de Calidad, Juran: determinar el "
 "tipo interna de cliente o de certificacion, definir si es a cumplimiento o a efectividad, "
 "seleccionar auditores independientes, establecer los estandares contra los que comparar) contra "
 "programa_auditoria_calidad (Programa de Auditoria de Calidad, Juran: definir si es a cumplimiento "
 "o efectividad, decidir auditar tu mismo o pedir externo, establecer el alcance de que partes y "
 "sistemas, documentar el proposito y las reglas en un documento que apruebas). MISMA FUENTE "
 "Juran, sim_tit 69,4. Comparten la orientacion cumplimiento contra efectividad y la eleccion de "
 "auditor, pero el primero es la TIPOLOGIA y el estandar de comparacion (que clases de auditoria "
 "hay); el segundo es el CHARTER del programa (alcance, documento aprobado). El cumulo de las "
 "auditorias separa cada nodo: programa =D= auditorias_proceso, auditoria_negocio, auditoria_calidad "
 "(2568, 2635, 2659); concepto =D= sus hermanos (2522, 2749). D. DISCUTIBLE MARCADO fuerte: sim_tit "
 "69,4 y comparten la orientacion y el auditor; quien pese ese nucleo dira A.")
add(2850, "D",
 "politica_no_culpar_trabajador (Evitar Culpar al Trabajador por Fallos del Sistema, Deming: "
 "analizar la distribucion de errores con limites de control, identificar quien excede el limite "
 "superior como posible causa especial, evitar sanciones uniformes, comunicar que el sistema no la "
 "persona responde por la variacion comun, disenar respuestas diferenciadas) contra "
 "responsabilidad_gerencial_causas_comunes (Tu responsabilidad sobre las causas comunes, Deming: "
 "distinguir comun de especial, usar graficos para el porcentaje de cada una, eliminar las frases "
 "motivacionales sin metodo, comprometerte por escrito a remover las barreras del sistema, "
 "comunicar que la persona solo responde por las causas especiales). MISMA FUENTE Deming, sim_tit "
 "38,1. D POR LA FRONTERA YA TRAZADA ENTRE LA DISTINCION Y LA POSTURA GERENCIAL: "
 "politica_no_culpar_trabajador vive en el cumulo de la distincion POR DERECHO (=A= "
 "distincion_causas_comunes_especiales 2736, =A= identificacion_causa_raiz_no_culpa 2766, =A= "
 "moral_y_sistema_no_individuo 2800), mientras responsabilidad_gerencial_causas_comunes es todo D, "
 "incluido =D= causas_comunes_vs_especiales (2677, el absorbedor de la distincion). El primero es "
 "el ACTO estadistico de no culpar; el segundo es la POSTURA gerencial con lemas y compromiso "
 "escrito de remover barreras, la faceta que el reporte 2800 dejo POR ELEGIR y separada. D. "
 "DISCUTIBLE MARCADO fuerte: la postura gerencial tambien usa graficos para comun contra especial; "
 "es la misma frontera de los discutibles 2766 y 2800, quien pese ese nucleo dira A.")

out = io.open("docs/loop/_lote.jsonl", "w", encoding="utf-8", newline="\n")
for x in lote:
    out.write(json.dumps(x, ensure_ascii=False) + "\n")
out.close()
print("escritos %d, %d..%d, clases %s" % (len(lote), lote[0]["puesto"], lote[-1]["puesto"],
      dict(collections.Counter(x["clase"] for x in lote))))
