# -*- coding: utf-8 -*-
# constructor del lote del tramo 2876-2900 (cierre del checkpoint 2900).
import json, io, collections
lote = []
def add(p, c, r):
    assert "—" not in r and "–" not in r, "guion largo en %d" % p
    lote.append({"puesto": p, "clase": c, "razon": r})

add(2876, "D",
 "fitness_for_purpose_vs_conformance (Fitness for Purpose vs Conformance, Juran: mapear la "
 "definicion de calidad del cliente contra la interna, identificar factores post venta no "
 "cubiertos por las especificaciones, revisar las especificaciones internas para la aptitud de "
 "uso, alinear las metricas con la experiencia del cliente) contra insuficiencia_especificaciones "
 "(La insuficiencia de cumplir solo con especificaciones, Deming: comunicar al proveedor el uso "
 "final, evaluar la compatibilidad e integracion de componentes en el sistema completo, disenar y "
 "probar subsistemas juntos, pedir retroalimentacion de ingenieria antes de fijar las "
 "especificaciones). FUENTES DISTINTAS, sim_tit 44,2. Ambos dicen que la especificacion no basta, "
 "pero por caras distintas: el primero por la APTITUD DE USO y la experiencia del cliente; el "
 "segundo por la INTEGRACION del sistema (componentes juntos, subsistemas). fitness_for_purpose es "
 "todo D en su familia (2542, 2680). D. DISCUTIBLE MARCADO: comparten la tesis de que cumplir la "
 "especificacion no alcanza; quien pese ese nucleo dira A.")
add(2877, "D",
 "benchmarking_mejores_practicas (Benchmarking de Mejores Practicas, Juran: identificar los "
 "procesos clave, seleccionar organizaciones mejores en su clase, hacer el estudio, identificar "
 "brechas) contra tipos_benchmarking_por_participante (Tipos de Benchmarking segun Participantes, "
 "interno externo competitivo: ver si hay operaciones internas duplicadas para benchmarking "
 "interno, evaluar si se necesitan competidores directos, determinar la confidencialidad, elegir "
 "el tipo que maximice el aprendizaje). MISMA FUENTE Juran, sim_tit 44,3. El primero es el ESTUDIO "
 "de mejores practicas (seleccionar los mejores, brechas); el segundo es la CLASIFICACION de los "
 "tipos de benchmarking por participante (interno, externo, competitivo). La familia del "
 "benchmarking separa cada nodo (2536, 2839, 2854, 2855). Elegir el tipo no es correr el estudio. "
 "D. DISCUTIBLE MARCADO: ambos preparan un benchmarking; quien pese ese marco dira A.")
add(2878, "D",
 "fijacion_de_metas (Fijar metas de mejora, Paso 10 de Crosby: una semana despues del Dia ZD cada "
 "grupo propone dos metas medibles, retadoras, publicarlas, reconocer, medidas de corto plazo) "
 "contra programa_mejora_calidad_14_pasos (Programa de Mejora de Calidad de 14 pasos, Crosby: "
 "comprometerte, reunir un equipo, definir la medicion y el costo de la no calidad, conciencia de "
 "calidad, accion correctiva sistematica, Dia de Cero Defectos, fijar metas y eliminar causas y "
 "reconocer y repetir el ciclo). MISMA FUENTE Crosby, sim_tit 47,9. FICHA CONTRA MAPA: "
 "fijacion_de_metas es UN paso (el 10); programa_14_pasos es el PROGRAMA entero que lo lista como "
 "uno de sus pasos (fijar metas). fijacion =A= establecimiento_metas (2699, su gemelo); "
 "programa_14_pasos =A= programa_de_mejora_de_calidad (2414) y =D= sus variantes. Un paso no es el "
 "programa de 14 pasos. D. DISCUTIBLE MARCADO: fijar metas vive dentro del programa; quien lo lea "
 "como contenido dira A.")
add(2879, "D",
 "disponibilidad_producto (Calculo de Disponibilidad del Producto, Juran: determinar el MTBF, "
 "determinar el MTTR o MDT, calcular la disponibilidad A igual MTBF sobre MTBF mas MDT, verificar "
 "los supuestos de tasa constante, diferenciar disponibilidad operacional de intrinseca) contra "
 "formula_exponencial_confiabilidad (Formula Exponencial de Confiabilidad y MTBF, Juran: verificar "
 "la tasa de fallo constante, calcular el MTBF del historico, aplicar R igual e a la menos t sobre "
 "mu, interpretar sin confundir con vida util, evaluar el impacto de cambios en el MTBF). MISMA "
 "FUENTE Juran, sim_tit 44,4. Miden cosas distintas con el mismo MTBF de fondo: el primero la "
 "DISPONIBILIDAD (tiempo arriba, MTBF mas MDT); el segundo la CONFIABILIDAD (probabilidad de no "
 "fallar, R exponencial). formula_exponencial =A= distribucion_exponencial (2624, su gemelo). "
 "Disponibilidad no es confiabilidad. D. DISCUTIBLE MARCADO: ambos son ingenieria de confiabilidad "
 "con MTBF; quien pese ese insumo comun dira A.")
add(2880, "D",
 "aprobacion_alta_direccion (Tu Compromiso Personal con el Cambio, Juran: reunir evidencia de "
 "amenazas competitivas, cuantificar con el costo de la mala calidad, definir que no puedes "
 "delegar, autorevisiones periodicas, reconocer un 10 por ciento mas de trabajo) contra "
 "compromiso_gerencial_calidad (Paso Uno, Compromiso de la Direccion, Crosby: reflexionar sobre la "
 "necesidad de mejorar poniendo el foco en prevenir, escribir una postura clara de calidad, "
 "confirmar que mejorar la calidad mejora las ganancias, no confundir el compromiso con frases "
 "motivadoras vacias). FUENTES DISTINTAS, sim_tit 52,8. Ambos son el compromiso gerencial con la "
 "calidad, pero cada marco trae pasos enteros propios: Juran las tareas no delegables y el 10 por "
 "ciento mas de trabajo; Crosby escribir la postura y el foco en prevenir. aprobacion =D= "
 "practicas_no_delegables (2738) e inhibidores (2840); compromiso =D= fijacion_de_metas (2743). D. "
 "DISCUTIBLE MARCADO fuerte: ambos son el compromiso de la direccion con el caso de negocio de la "
 "calidad; quien pese ese nucleo dira A.")
add(2881, "D",
 "distincion_causas_comunes_especiales_2 (Distincion entre Causas Comunes y Especiales, Deming: "
 "antes de investigar un defecto revisar el control con una carta, si esta en control reconocer "
 "que la variacion es de causa comun, evitar investigar cada caso como especial, dirigir la mejora "
 "al cambio estructural del sistema) contra responsabilidad_gerencial_causas_comunes (Tu "
 "responsabilidad sobre las causas comunes, Deming: distinguir comun de especial, usar graficos "
 "para el porcentaje, eliminar las frases motivacionales sin metodo, comprometerte por escrito a "
 "remover las barreras, comunicar que la persona solo responde por las especiales). MISMA FUENTE "
 "Deming, sim_tit 47,2. LA MISMA FRONTERA DEL 2850: distincion_2 vive en el cumulo de la "
 "distincion POR DERECHO (=A= causas_comunes_vs_especiales 2497, =A= distincion_causas_especiales_"
 "comunes 2532, =A= distincion_causas_comunes_especiales 2752), mientras responsabilidad_gerencial "
 "es todo D, incluido =D= causas_comunes_vs_especiales (2677, el absorbedor). El primero es el "
 "ACTO estadistico de la distincion; el segundo la POSTURA gerencial con lemas y compromiso "
 "escrito. D. DISCUTIBLE MARCADO fuerte: la postura tambien usa graficos para comun contra "
 "especial; misma frontera de los discutibles 2766, 2800 y 2850, quien pese ese nucleo dira A.")
add(2882, "D",
 "herramientas_analisis_causa_raiz (Herramientas Graficas de Analisis de Datos, menu de graficos "
 "histogramas box plots Pareto dispersion estratificacion: recolectar, seleccionar la herramienta, "
 "construir y analizar, Pareto para priorizar, estratificar) contra resumen_de_datos_graficos "
 "(Resumen y Visualizacion Grafica de Datos: graficar la salida contra el tiempo, histograma, box "
 "plots, medidas de tendencia y dispersion, buscar tendencias). MISMA FUENTE Juran, sim_tit 35,1. "
 "Dos conjuntos de herramientas graficas que la familia separa: herramientas =D= sus hermanos "
 "(2647, 2720, 2757, 2844) y resumen =D= los suyos (2538, 2750, 2869). El primero acentua Pareto y "
 "estratificacion para la causa raiz; el segundo la serie temporal y las medidas resumen. D. "
 "DISCUTIBLE MARCADO: comparten histograma y box plot; quien pese ese solape dira A.")
add(2883, "D",
 "analisis_de_sistemas_de_medicion_msa (Analisis de Sistemas de Medicion MSA, Juran: definir el "
 "metodo de prueba, identificar las fuentes de variabilidad, verificar el control del proceso de "
 "medicion con carta, Gauge R&R con varios apraisers partes y repeticiones, calcular 5,15 sigma "
 "contra la especificacion, calibrar si hay sesgo) contra control_estadistico_metodo_medicion "
 "(Control Estadistico del Metodo de Medicion, Deming: mediciones repetidas del mismo item con el "
 "mismo operador en un R chart, verificar el control del rango, comparar operadores con el mismo "
 "instrumento, comparar instrumentos con el mismo operador, criterios de reproducibilidad, "
 "rechazar el metodo si no hay control). FUENTES DISTINTAS, sim_tit 46,6. Ambos validan el sistema "
 "de medicion via carta de control y comparacion entre operadores e instrumentos, pero el MSA es "
 "el estudio formal cuantitativo (Gauge R&R, 5,15 sigma, calibrar); el de Deming es la CONDICION "
 "de validez (poner el metodo en control y RECHAZARLO si no es reproducible). MSA =A= "
 "errores_de_medicion (2727, lo contiene). D. DISCUTIBLE MARCADO fuerte: el metodo de Deming cabe "
 "casi entero en el paso 3 y 4 del MSA (control y comparacion de operadores); quien lea eso como "
 "contencion dira A.")
add(2884, "D",
 "capacidad_de_proceso (Capacidad de Proceso, Juran: recolectar datos historicos, calcular los "
 "indices de capacidad contra especificaciones, decidir la frecuencia de medicion, determinar si "
 "necesita rediseno o es apto) contra establecimiento_capacidad_proceso (Establecimiento de la "
 "Capacidad del Proceso Mejorado, Juran: decidir como probar las mejoras, plan de prueba por "
 "mejora, conducir la prueba, ajustar si no satisface, confirmar el control con cartas, hacer el "
 "analisis de capacidad). MISMA FUENTE Juran, sim_tit 55,6. LA FAMILIA DE LA CAPACIDAD, SIN ACTO y "
 "toda D: capacidad_de_proceso =D= sus variantes (2412, 2591, 2636, 2779); "
 "establecimiento_capacidad =D= las suyas (2423, 2697). El primero CALCULA la capacidad actual; el "
 "segundo PRUEBA las mejoras y luego hace el analisis. D. DISCUTIBLE MARCADO: ambos terminan en un "
 "analisis de capacidad; quien pese ese cierre comun dira A.")
add(2885, "D",
 "definicion_calidad_conformidad (Calidad como Conformidad con los Requisitos, Crosby: definir "
 "requisitos medibles, eliminar terminos subjetivos, comunicar con precision, evaluar por si "
 "cumple o no, corregir un requisito poco realista al definirlo, preguntar que requisito evalua "
 "quien habla vago) contra definicion_calidad_fitness_for_purpose (Definicion de Calidad como "
 "Fitness for Purpose, Juran: identificar al cliente final, determinar sus necesidades explicitas "
 "e implicitas, traducirlas en caracteristicas, documentar las fallas que afectan la percepcion, "
 "verificar el diseno libre de fuentes de falla, comunicarlo a proveedores). FUENTES DISTINTAS, "
 "sim_tit 43,9. Son las DOS definiciones OPUESTAS de calidad, el debate del doble significado: "
 "conformidad con requisitos (Crosby) contra aptitud para el uso (Juran). definicion_conformidad "
 "=D= concepto_haciendo (2866); fitness_for_purpose es todo D (2494, 2650, 2734). D. DISCUTIBLE "
 "MARCADO: ambos son la definicion de calidad; quien ignore que son definiciones contrapuestas "
 "dira A.")
add(2886, "D",
 "definicion_calidad_segun_agente (La Calidad Depende de Quien la Juzgue, Deming: identificar a "
 "todos los que juzgan la calidad, determinar que entiende cada uno por buena calidad, anotar los "
 "desacuerdos, priorizar las caracteristicas por impacto) contra "
 "identificacion_del_verdadero_cliente (Identificacion del Verdadero Cliente, Deming: mapear la "
 "cadena de actores antes del usuario final, determinar quien tiene poder de rechazo en cada "
 "etapa, disenar las especificaciones considerando a todos los decisores). MISMA FUENTE Deming, "
 "sim_tit 46,5. Actos distintos: el primero es que la calidad se JUZGA distinto segun quien "
 "(definiciones divergentes, desacuerdos); el segundo es IDENTIFICAR al verdadero cliente (la "
 "cadena, quien tiene poder de rechazo). Mapear quien decide no es catalogar las definiciones "
 "divergentes de calidad. D. DISCUTIBLE MARCADO: ambos identifican a los actores que deciden la "
 "calidad; quien pese ese paso comun dira A.")
add(2887, "A",
 "secuencia_universal_para_el_breakthrough (Secuencia Universal de Juran para el Breakthrough, "
 "Juran: nominar los problemas prioritarios, establecer un proyecto formal con equipo, diagnosticar "
 "la causa raiz por el viaje diagnostico, disenar y probar remedios por el viaje remedial, poner "
 "controles nuevos, replicar y nominar nuevos) contra six_sigma_dmaic (Modelo Six Sigma DMAIC: "
 "seleccionar el problema con plazo, definirlo claro, medir los sintomas con datos, analizar hasta "
 "la causa raiz, implementar el remedio dirigido a esa causa, controlar los resultados). MISMA "
 "FUENTE Juran, con arista, sim_tit 25,0 solo por los titulos. A POR LA IDENTIDAD BREAKTHROUGH "
 "IGUAL DMAIC, ya doctrina: breakthrough_desempeno_actual =A= six_sigma_dmaic (2618) y =A= "
 "six_sigma_dmaic_2 (2759), y six_sigma_dmaic =A= six_sigma_dmaic_2 (2548). La Secuencia Universal "
 "es el ancestro del DMAIC y sus pasos calzan uno a uno: nominar y proyecto igual Definir, viaje "
 "diagnostico igual Medir y Analizar, viaje remedial igual Mejorar, controles igual Controlar. "
 "secuencia_universal_para_el =A= secuencia_universal_breakthrough (2781, su gemelo). A por "
 "transitividad de esa identidad, no mueve el contador (ambos en cumulos ya contados). DISCUTIBLE "
 "MARCADO fuerte: sim_tit 25,0 y el vocabulario difiere (los dos viajes y nominar contra las cinco "
 "letras); quien lea esa estructura como distinta dira D.")
add(2888, "A",
 "distincion_causas_comunes_especiales (Distincion entre Causas Comunes y Especiales de Variacion, "
 "Deming: ver si el trabajo esta en control con graficos, si esta en control no informar defectos "
 "individuales y enfocar el sistema, si hay causa especial ayudar a identificarla, evitar sanciones "
 "por fallas del sistema) contra variacion_del_sistema_vs_individuo (Cuando la diferencia entre "
 "personas es el sistema, Deming: recopilar el desempeno de un grupo, calcular los limites "
 "atribuibles al sistema, ver quien cae fuera para bien o mal, para los de dentro mejorar el "
 "sistema no calificar a la persona, para los de fuera investigar causas especificas). MISMA "
 "FUENTE Deming, sim_tit 39,4. Es el MISMO ACTO de la distincion aplicada a las personas: poner el "
 "desempeno en limites de control, los de dentro son causa comun del sistema (mejorar el sistema, "
 "no culpar), los de fuera son causa especial (investigar). distincion_causas_comunes_especiales "
 "vive en el cumulo de la distincion POR DERECHO (=A= politica_no_culpar 2736, =A= causas_comunes_"
 "vs_especiales 2501, =A= distincion_causas_especiales_comunes 2740, =A= _2 2752). variacion entra "
 "al mismo cumulo. A POR DERECHO, no mueve el contador (transitividad al cumulo ya contado). "
 "DISCUTIBLE MARCADO: variacion pone limites sobre un GRUPO de personas; quien lea ese encuadre "
 "como metodo aparte dira D.")
add(2889, "D",
 "distribucion_exponencial (Distribucion Exponencial para Confiabilidad, Juran: estimar el MTBF, "
 "calcular la razon X sobre mu, consultar la tabla de area exponencial para la probabilidad de "
 "superar un tiempo sin fallo, usarlo para mantenimiento o garantias) contra distribucion_weibull "
 "(Distribucion Weibull para Prediccion de Vida Util, Juran: obtener al menos 7 mediciones de vida "
 "a fatiga, calcular los rangos medios, graficar en papel de probabilidad Weibull, ajustar la "
 "recta y estimar el parametro de forma beta, extrapolar con cautela, verificar con Anderson "
 "Darling). MISMA FUENTE Juran, con arista, sim_tit 50,0. DOS DISTRIBUCIONES DISTINTAS: la "
 "exponencial (tasa de fallo constante, tabla de area) contra la Weibull (parametro de forma, "
 "papel de probabilidad, vida a fatiga). distribucion_exponencial =A= formula_exponencial (2624) "
 "pero =D= weibull_confiabilidad (2503); distribucion_weibull =D= weibull_confiabilidad (2468). "
 "Metodos y supuestos distintos. D. DISCUTIBLE MARCADO: ambas son distribuciones de confiabilidad "
 "con arista; quien pese ese parentesco dira A.")
add(2890, "D",
 "analisis_capacidad_procesos (Analisis de Capacidad de Proceso mediante Histogramas, Juran: "
 "muestra de al menos 40 mediciones, histograma con los limites de especificacion, evaluar el "
 "centrado, evaluar el ancho contra las especificaciones, evaluar la forma y los picos multiples "
 "como mezcla, determinar si es capaz) contra capacidad_del_proceso (Capacidad del Proceso, "
 "Deming: verificar primero el control estadistico, calcular la media y el rango promedio del "
 "proceso estable, determinar la capacidad con las constantes d2 A2, comunicar la capacidad real a "
 "diseno). FUENTES DISTINTAS, sim_tit 54,1. LA FAMILIA DE LA CAPACIDAD, SIN ACTO y toda D: "
 "capacidad_del_proceso =D= sus variantes (2412, 2535, 2569, 2751). El primero estima la capacidad "
 "por HISTOGRAMA (centrado, ancho, forma); el segundo por las CONSTANTES de la carta (d2, A2). "
 "Metodos distintos. D. DISCUTIBLE MARCADO: ambos determinan si el proceso es capaz contra las "
 "especificaciones; quien pese ese objetivo comun dira A.")
add(2891, "A",
 "estadistico_competente_organizacion (Rol del Estadistico Competente en la Organizacion, Deming: "
 "evaluar si hay personal capacitado en estadistica, otorgar autoridad transversal para investigar "
 "cualquier proceso, programas de capacitacion en pensamiento estadistico para todos, integrar al "
 "estadistico en decisiones de diseno compras y control) contra organizacion_liderazgo_estadistico "
 "(Organizacion para el Liderazgo de Metodologia Estadistica, Deming: definir quien es responsable "
 "del metodo estadistico con autoridad para revisar cualquier area, exigir dominio real, que cada "
 "quien responda por su dia a dia ante su area pero por el metodo ante el lider estadistico, "
 "asegurar su presencia en las decisiones importantes, no dejar que las decisiones con datos las "
 "juzgue solo el criterio del area). MISMA FUENTE Deming, sim_tit 53,1. A POR FUSION MUTUA: el "
 "acto entero compartido es instalar a un lider estadistico competente con autoridad transversal "
 "sobre todas las areas e integrado en las decisiones importantes; eso es el nodo entero en ambos. "
 "Cada uno pone su linea propia (la capacitacion para todos en uno, la doble linea de reporte en "
 "el otro), en los dos sentidos. NUEVO CASO DE FUSION MUTUA, superviviente POR ELEGIR fuera de "
 "cumulo contado: mueve el contador a DIECIOCHO (el anterior fue el 2.666). DISCUTIBLE MARCADO "
 "fuerte: la capacitacion para todos y la doble linea de reporte son pasos enteros propios; quien "
 "pese eso por la vara del paso entero dira D.")
add(2892, "D",
 "eliminacion_causas_error (Eliminacion de Causas de Error, Paso 11, Crosby: formulario de una "
 "pagina para reportar obstaculos, grupos funcionales que resuelven cada tipo, acuse dentro de 24 "
 "horas, seguimiento y comunicar soluciones) contra eliminacion_causas_error_4 (Eliminacion de "
 "Causas de Error ECR, Crosby: canal con formulario para reportar sin proponer solucion, "
 "agradecimiento personal inmediato, clasificar y priorizar y rutear, conseguir recursos y actuar "
 "rapido, si no actuas justificar y revisar con alguien, confirmar la decision y reconocer a "
 "quienes mas avisan). MISMA FUENTE Crosby, sim_tit 69,4. D POR TRANSITIVIDAD: "
 "eliminacion_causas_error =D= eliminacion_causas_error_2 (2416) mientras eliminacion_causas_"
 "error_4 =A= eliminacion_causas_error_2 (2557), asi que error y _4 caen a lados distintos. El "
 "primero acentua la RESOLUCION por grupos funcionales con acuse a 24 horas; el _4 (y el _2) el "
 "LAZO del que reporta (agradecer, justificar si no actuas, reconocer). D. DISCUTIBLE MARCADO "
 "fuerte: sim_tit 69,4 y ambos son la ECR del Paso 11 casi identica; la lectura ingenua dira A; la "
 "transitividad via el _2 la vuelve D.")
add(2893, "D",
 "kaizen_mejora_continua (Kaizen y Eventos de Mejora Rapida, Juran: seleccionar un proceso con "
 "desperdicio del VSM, organizar un evento kaizen con equipo multidisciplinario, cambios "
 "inmediatos en dias, medir el impacto antes y despues, estandarizar e institucionalizar) contra "
 "ocho_desperdicios_lean (Los Ocho Desperdicios de Lean de Ohno, Juran: mapear el proceso "
 "identificando cada uno de los ocho tipos, cuantificar su impacto, priorizar los de mayor "
 "impacto, disenar contramedidas por tipo, redisenar eliminando pasos sin valor, medir el "
 "impacto). MISMA FUENTE Juran, sim_tit 36,8. Actos distintos: el primero es el EVENTO kaizen de "
 "mejora rapida (organizar, cambios en dias, estandarizar); el segundo es la TAXONOMIA de los ocho "
 "desperdicios (identificar cada tipo, contramedidas, redisenar). kaizen =D= eventos_kaizen_rie "
 "(2466); ocho_desperdicios =D= introduccion_lean (2665). D. DISCUTIBLE MARCADO: ambos atacan el "
 "desperdicio Lean; quien pese ese marco dira A.")
add(2894, "D",
 "mantenimiento_productivo_total (Mantenimiento Productivo Total TPM y RCM, Juran: formar equipos "
 "multidisciplinarios de mantenimiento, identificar problemas que afectan la capacidad, mejoras "
 "incrementales de mantenimiento preventivo y correctivo, medir el OEE) contra "
 "rcm_reliability_centered_maintenance (Mantenimiento Centrado en Confiabilidad RCM, Juran: "
 "clasificar los activos por criticidad reactivo preventivo predictivo, para los reactivos operar "
 "hasta la falla, para los preventivos calendario por tiempo, para los predictivos monitoreo de "
 "condicion, medir el OEE). MISMA FUENTE Juran, sim_tit 69,8. Dos metodologias distintas de "
 "mantenimiento: el TPM (equipos, mejoras incrementales, OEE) contra el RCM (clasificar activos "
 "por criticidad y estrategia diferenciada). El contenido del primero es TPM aunque su titulo "
 "nombre el RCM; el segundo es el RCM entero. mantenimiento_productivo_total =D= tpm_maintenance "
 "(2550). D. DISCUTIBLE MARCADO fuerte: el titulo del primero incluye RCM y ambos miden OEE, "
 "sim_tit 69,8; quien lea eso como el mismo mantenimiento dira A.")
add(2895, "D",
 "muestreo_dodge_romig (Tablas de Muestreo Dodge Romig, LTPD y AOQL, Juran: ver si se prioriza la "
 "proteccion lote por lote LTPD o el promedio a largo plazo AOQL, seleccionar el valor deseado, "
 "consultar la tabla para el tamano de muestra y el numero de aceptacion, inspeccion 100 por "
 "ciento con reemplazo para los lotes rechazados) contra niveles_calidad_muestreo_aql_lql_aoql "
 "(Indices de Calidad para Planes de Muestreo AQL LQL IQL AOQL: definir el AQL, fijar el LQL o "
 "LTPD y el riesgo del consumidor, calcular el AOQL, comunicar que el AQL no autoriza no "
 "conforme). MISMA FUENTE Juran, sim_tit 50,0. El primero es el PROCEDIMIENTO de las tablas Dodge "
 "Romig (elegir LTPD o AOQL, leer la tabla, 100 por ciento con reemplazo); el segundo es la "
 "DEFINICION de los indices (que significan AQL, LQL, AOQL). Como en 2831, definir los indices no "
 "es aplicar la tabla. niveles =D= sus hermanos (2795, 2831). D. DISCUTIBLE MARCADO: las tablas "
 "usan LTPD y AOQL que el otro define; quien lea eso como contencion dira A.")
add(2896, "D",
 "acreditacion_organismos_certificadores (Acreditacion de Organismos Certificadores y "
 "Reconocimiento Mutuo, Juran: verificar que el certificador este acreditado por un organismo "
 "reconocido, confirmar los acuerdos de reconocimiento mutuo entre origen y destino, evaluar "
 "certificadores multiacreditados si operas en varios paises) contra "
 "certificacion_registro_sistema_calidad (Certificacion y Registro, Auditorias de Tercera Parte, "
 "Juran: elegir el estandar como ISO 9001, implementar el sistema conforme a la norma, revisar tu "
 "mismo antes de la auditoria, contratar un certificador acreditado, obtener el certificado y "
 "registrarte, superar las auditorias de vigilancia). MISMA FUENTE Juran, con arista, sim_tit "
 "47,7. FICHA CONTRA MAPA: acreditacion es UNA preocupacion (que el certificador este acreditado, "
 "reconocimiento mutuo) dentro del proceso de certificacion, cuyo paso 4 es justo contratar un "
 "certificador acreditado; certificacion_registro es el PROCESO entero (norma, implementar, "
 "auditoria, registro, vigilancia). certificacion_registro =D= sus hermanas (2543, 2657). D. "
 "DISCUTIBLE MARCADO: acreditacion es el detalle del paso 4; quien lo lea como contenido dira A.")
add(2897, "A",
 "distincion_causas_comunes_especiales_incidentes (Distincion entre Causas Comunes y Especiales en "
 "el Analisis de Accidentes, Deming: recopilar los incidentes en un grafico de control, ver si "
 "caen dentro de los limites del sistema, evitar atribuir a negligencia individual sin analisis, "
 "si es del sistema redisenar en vez de sancionar, documentar la proporcion sistemica contra "
 "especial) contra distincion_causas_especiales_comunes (Distincion, Teorema de Nelson, Deming: "
 "antes de ajustar verificar el control, rastrear causas periodicas o recurrentes por registros, "
 "evitar tratar cada defecto como especial si el sistema es estable, usar metodos estadisticos "
 "para decidir la intervencion). MISMA FUENTE Deming, sim_tit 75,9. AMBOS EN EL CUMULO DE LA "
 "DISTINCION POR DERECHO: distincion_incidentes =A= causas_comunes_vs_especiales (2641) y "
 "distincion_causas_especiales_comunes =A= causas_comunes_vs_especiales (2577), asi que fusionan. "
 "Es la misma distincion comun contra especial, uno aplicado a accidentes y el otro el Teorema de "
 "Nelson. A por el cumulo POR DERECHO, no mueve el contador. DISCUTIBLE MARCADO: el de accidentes "
 "trae documentar la proporcion sistemica; quien lea ese encuadre como cara distinta dira D.")
add(2898, "D",
 "descubrir_necesidades_del_cliente (Descubrimiento de las Necesidades del Cliente, Juran: "
 "planificar los metodos de recoleccion, recopilar las necesidades en el lenguaje del cliente, "
 "distinguir declaradas reales percibidas y culturales, investigar usos no previstos y riesgos, "
 "analizar y priorizar, traducir al lenguaje tecnico) contra identificar_clientes_externos_e_"
 "internos (Identificacion de Clientes Externos e Internos, Juran: diagrama de flujo del proceso, "
 "listar clientes externos compradores usuarios comerciantes ocultos, identificar clientes "
 "internos por la relacion proveedor procesador cliente, distinguir quien ordena de quien usa). "
 "MISMA FUENTE Juran, con arista, sim_tit 50,5. D POR TRANSITIVIDAD: descubrir_necesidades =D= "
 "identificar_clientes_diseno (2644) mientras identificar_clientes_externos =A= "
 "identificar_clientes_diseno (2673), asi que caen a lados distintos. Son dos pasos del cascadeo: "
 "IDENTIFICAR a los clientes contra DESCUBRIR sus necesidades. descubrir =A= su gemelo "
 "descubrir_necesidades_cliente (2461). Identificar a quien es el cliente no es descubrir que "
 "necesita. D. DISCUTIBLE MARCADO: son pasos consecutivos con arista; quien lea el cascadeo como "
 "un solo acto dira A.")
add(2899, "D",
 "accion_correctiva_6 (Accion Correctiva, Destapar Causas Rolling Over the Rocks, Crosby: "
 "documentar via auditorias de calidad, investigar la causa raiz, asignar responsables y plazos, "
 "verificar que se elimino) contra eliminacion_causas_error_2 (Eliminacion de Causas de Error ECR, "
 "Paso 11, Crosby: distribuir formularios de una pagina en cada area, agradecimiento inmediato al "
 "que presenta un ECR, tomar en serio cada uno, si no actuas validar con alguien, responder "
 "rapido, incentivos como un sorteo semanal). MISMA FUENTE Crosby, sim_tit 37,7. Son DOS pasos "
 "distintos del programa Crosby: la accion correctiva Paso 6 (auditoria, causa raiz, asignar, "
 "verificar) contra la eliminacion de causas de error Paso 11 (el formulario donde el trabajador "
 "avisa obstaculos, agradecer, incentivar). accion_correctiva_6 vive en el cumulo A del Paso 6 "
 "pero =D= lo ajeno (2717, 2755, 2808); eliminacion_causas_error_2 =A= _4 (2557) y =D= error "
 "(2416). D. DISCUTIBLE MARCADO: ambos reportan y resuelven problemas de calidad; quien pese ese "
 "patron dira A.")
add(2900, "D",
 "conformidad_especificacion_aptitud_uso (Conformidad a Especificacion y Aptitud para el Uso, "
 "Juran: medir el output contra los requisitos, determinar si el no conforme es apto para uso por "
 "consulta multidisciplinaria, decidir la disposicion rechazo reproceso o uso condicional, "
 "comunicar la decision) contra disposicion_producto_no_conforme (Disposicion de Producto No "
 "Conforme, Juran: marcar el lote hold y a cuarentena, asignar un investigador de aptitud para el "
 "uso, decidir la disposicion final reparar reclasificar desechar o waiver, documentar via el "
 "material review board, registrar el porcentaje de lotes bajo waiver). MISMA FUENTE Juran, "
 "sim_tit 47,1. Comparten la decision de aptitud para el uso del no conforme, pero cada uno trae "
 "su acto propio: el primero arranca MIDIENDO contra la especificacion (la conformidad); el "
 "segundo es la MAQUINARIA de disposicion (cuarentena, MRB, seguimiento del porcentaje de "
 "waivers). conformidad_especificacion es todo D en su familia (2492, 2684, 2711). D. DISCUTIBLE "
 "MARCADO: ambos deciden la disposicion del no conforme por aptitud para el uso; quien pese ese "
 "nucleo dira A.")

out = io.open("docs/loop/_lote.jsonl", "w", encoding="utf-8", newline="\n")
for x in lote:
    out.write(json.dumps(x, ensure_ascii=False) + "\n")
out.close()
print("escritos %d, %d..%d, clases %s" % (len(lote), lote[0]["puesto"], lote[-1]["puesto"],
      dict(collections.Counter(x["clase"] for x in lote))))
